#!/usr/bin/env bash

# Load crontabs from directory if cron.directory attribute is set

if test $(flux getattr rank) -eq 0 \
	&& cron_dir=$(flux getattr cron.directory 2>/dev/null) \
	&& test -d "$cron_dir"; then
	shopt -s nullglob
	for file in $cron_dir/*; do
		if test -f $file; then
			if ! flux cron tab <$file; then
				echo "could not load crontab: $file" >&2
				exit 1
			fi
		fi
	done
	shopt -u nullglob
fi
