#!/bin/bash

# Populate resource.hosts for this instance using either R_lite
#  from the parent instance if this is a flux job, or flux-exec hostname
#
if test -n "${FLUX_JOB_ID}"; then
    FLUX_URI=$(flux getattr parent-uri) flux hostlist ${FLUX_JOB_ID} | \
	flux hostlist --set
else
    flux hostlist | flux hostlist --set
fi
