flux_rpc_multi(3)
=================
:doctype: manpage


NAME
----
flux_rpc_multi, flux_rpc_next, flux_rpc_get_nodeid - send a remote procedure call to a Flux service on multiple ranks


SYNOPSIS
--------
#include <flux/core.h>

flux_rpc_t *flux_rpc_multi (flux_t *h, const char *topic, const char *json_str,
                            const char *nodeset, int flags);

int flux_rpc_next (flux_rpc_t *rpc);

int flux_rpc_get_nodeid (flux_t *h, uint32_t *nodeid);

DESCRIPTION
-----------

`flux_rpc_multi()` encodes and sends request messages, comprising the
first half of a remote procedure call (RPC), to multiple ranks.
A flux_rpc_t object is returned which can be passed repeatedly to
`flux_rpc_get()` to obtain the decoded response messages, comprising
the second half of the RPC.  The flux_rpc_t should finally be disposed
of using `flux_rpc_destroy()`.

_topic_ must be set to a topic string representing the Flux
service that will handle the request.

_json_in_, if non-NULL, must be a string containing valid serialized
JSON to be attached as payload to the request.  If NULL, the request
will be sent without a payload.

_nodeset_ is a string containing a bracketed set of ranks or "all" as a
shorthand for all ranks in the session.  Examples of valid nodeset
strings are "[0-255]", "[1,2.3]", and "[0,3,5-10]".

_flags_ may be zero or:

FLUX_RPC_NORESPONSE::
No response is expected.  The request will not be assigned a matchtag,
and the flux_rpc_t returned by `flux_rpc()` may be immediately destroyed.

`flux_rpc_get()` blocks until a matching response is received, then
decodes the result.  For asynchronous response handling,
see flux_rpc_then(3).

`flux_rpc_next()` invalidates the last-received message and payload
returned by `flux_rpc_get()`, and returns 0 if more responses are received.
Once all responses have been received, `flux_rpc_next()` returns -1;
thus it may be used as the conditional on a do-while loop, e.g.
....
do {
    flux_rpc_get (rpc, &payload);
} while (flux_rpc_next (rpc) == 0);
....

`flux_rpc_get_nodeid()` blocks until a matching response is received, then
decodes the nodeid in the response message.  If the remote service returned
a response containing an error, `flux_rpc_get_nodeid()` will succeed,
while `flux_rpc_get()` will fail.  This allows the failing nodeid to
be determined.

RETURN VALUE
------------

`flux_rpc_multi()` returns a flux_rpc_t object on success.  On error, NULL
is returned, and errno is set appropriately.

`flux_rpc_next()` returns 0 if additional responses are expected, else -1.
It does not set errno.

`flux_rpc_get_nodeid()` returns 0 on success;  on failure, it returns -1
and sets errno appropriately.


ERRORS
------

ENOSYS::
Handle has no send operation.

EINVAL::
Some arguments were invalid.

EPROTO::
A protocol error was encountered.


IMPLEMENTATION NOTES
--------------------

In the flux-core-0.0.1 implementation of `flux_rpc_multi()`, all requests
are sent back to back during the `flux_rpc_multi()` call, and routed
over the flux-broker(1) ring network, which is characterized by worst-case
latency that scales linearly with the session size.

Since requests are sent back to back without waiting for a response,
this message latency may be well hidden, but messages may flood the brokers
and overlay channels, since there is no flow control of requests based on
the timing of return messages.

Other options with different scalability properties are available.
For example, `flux_mrpc_*()` uses multicast events for synchronization
and the KVS with its hierarchical object cache for exchanging request
and response payloads.


EXAMPLE
-------

This example performs an RPC with the broker's "cmb.attrget" service on all
ranks.  A continuation is registered to process the responses as they arrive.
The reactor loop terminates once the RPC is completed since the completion
is its only event handler.

....
include::trpc_then_multi.c[]
....


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
---------
flux_rpc(3), flux_rpc_then(3)

https://github.com/flux-framework/rfc/blob/master/spec_6.adoc[RFC 6: Flux
Remote Procedure Call Protocol]
