flux_reactor_create(3)
======================
:doctype: manpage


NAME
----
flux_reactor_create, flux_reactor_destroy, flux_reactor_run, flux_reactor_stop, flux_reactor_stop_error - create/destroy/control event reactor object


SYNOPSIS
--------
#include <flux/core.h>

flux_reactor_t *flux_reactor_create (int flags);

void flux_reactor_destroy (flux_reactor_t *r);

int flux_reactor_run (flux_reactor_t *r, int flags);

void flux_reactor_stop (flux_reactor_t *r);

void flux_reactor_stop_error (flux_reactor_t *r);


DESCRIPTION
-----------

`flux_reactor_create()` creates a flux_reactor_t object which can be used
to monitor for events on file descriptors, ZeroMQ sockets, timers, and
flux_t broker handles.

There is currently only one possible flag for reactor creation:

FLUX_REACTOR_SIGCHLD::
  The reactor will internally register a SIGCHLD handler and be capable
  of handling flux child watchers (see flux_child_watcher_create(3)).

For each event source and type that is to be monitored, a flux_watcher_t
object is created using a type-specific create function, and started
with flux_watcher_start(3).

For each event source and type that is to be monitored, a flux_watcher_t
object is created and associated with a specific reactor using a type-specific
create function, and started with flux_watcher_start(3). To receive events,
control must be transferred to the reactor event loop by calling
`flux_reactor_run()`.

The full list of flux reactor run flags is as follows:

FLUX_REACTOR_NOWAIT::
  Return after all outstanding events have been consumed.  If there are remaining
  registered watchers, flux_reactor_run() will return an error.  See RETURN VALUE.
FLUX_REACTOR_ONCE::
  Return after at least on event has occurred, and all outstanding
  events have been consumed.  If there are remaining registered watchers,
  flux_reactor_run() will return an error.  See RETURN VALUE.

flux_reactor_run() processes events until one of the following conditions is met:

* There are no more active watchers.
* The `flux_reactor_stop()` or `flux_reactor_stop_error()` functions
  are called by one of the watchers.
* Flags include FLUX_REACTOR_NOWAIT and all outstanding events have
  been consumed
* Flags include FLUX_REACTOR_ONCE, at least one event has occurred,
  and all outstanding events have been consumed.

If `flux_reactor_stop_error()` is called, this will cause
`flux_reactor_run()` to return -1 indicating that an error has occurred.
The caller should ensure that a valid error code has been assigned to
errno(3) before calling this function.

`flux_reactor_destroy()` releases an internal reference taken at
`flux_reactor_create()` time.  Freeing of the underlying resources will
be deferred if there are any remaining watchers associated with the reactor.

RETURN VALUE
------------

`flux_reactor_create()` returns a flux_reactor_t object on success.
On error, NULL is returned, and errno is set appropriately.

`flux_reactor_run()` returns zero on normal termination.
On failure, termination by `flux_reactor_stop_error()` -1 is returned
with errno set.  Additionally if either FLUX_REACTOR_NOWAIT or FLUX_REACTOR_ONCE
is set and there are still watchers registered -1 is returned and errno set
to EWOULDBLOCK.


ERRORS
------

ENOMEM::
Out of memory.


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
---------
flux_fd_watcher_create(3), flux_handle_watcher_create(3),
flux_zmq_watcher_create(3), flux_timer_watcher_create(3),
flux_watcher_start(3)

http://software.schmorp.de/pkg/libev.html[libev home page]
