flux_rpc(3)
===========
:doctype: manpage


NAME
----
flux_rpc, flux_rpc_pack, flux_rpc_raw, flux_rpc_message, flux_rpc_get, flux_rpc_get_unpack, flux_rpc_get_raw - perform a remote procedure call to a Flux service


SYNOPSIS
--------
 #include <flux/core.h>

 flux_future_t *flux_rpc (flux_t *h, const char *topic,
                          const char *s,
                          uint32_t nodeid, int flags);

 flux_future_t *flux_rpc_pack (flux_t *h, const char *topic,
                               uint32_t nodeid, int flags,
                               const char *fmt, ...);

 flux_future_t *flux_rpc_raw (flux_t *h, const char *topic,
                              const void *data, int len,
                              uint32_t nodeid, int flags);

 flux_future_t *flux_rpc_message (flux_t *h,
                                  const flux_msg_t *msg,
                                  uint32_t nodeid, int flags);

 int flux_rpc_get (flux_future_t *f, const char **s);

 int flux_rpc_get_unpack (flux_future_t *f, const char *fmt, ...);

 int flux_rpc_get_raw (flux_future_t *f,
                       const void **data, int *len);

DESCRIPTION
-----------

A remote procedure call (RPC) consists of a matched request and
response message exchanged with a Flux service.  `flux_rpc()`,
`flux_rpc_pack()`, and `flux_rpc_raw()` encode and send a request message
via Flux broker handle _h_ to a Flux service identified by _topic_
and _nodeid_.  A `flux_future_t` object is returned which acts as a handle
for synchronization and a container for the response message which in
turn contains the RPC result.

A lower-level variant of `flux_rpc()`, `flux_rpc_message()` accepts a
pre-created request message, assigning _nodeid_ and matchtag according
to _flags_.

`flux_future_then(3)` may be used to register a reactor callback
(continuation) to be called once the response has been received.
`flux_future_wait_for(3)` may be used to block until the
response has been received.  Both accept an optional timeout.

`flux_rpc_get()`, `flux_rpc_get_unpack()`, and `flux_rpc_get_raw()`
decode the RPC result.  Internally, they call `flux_future_get()`
to access the response message stored in the future.  If the response
message has not yet been received, these functions block until it is,
or an error occurs.


REQUEST OPTIONS
---------------

The request message is encoded and sent with or without a payload
using one of the three `flux_rpc()` variants.

`flux_rpc()` attaches _s_, a NULL terminated string, as request
payload.  If NULL, the request is encoded without a payload.

`flux_rpc_pack()` attaches a JSON payload encoded as a NULL terminated
string using Jansson `json_pack()` style arguments (see below).

`flux_rpc_raw()` attaches a raw payload _data_ of length _len_, in bytes.
If _data_ is NULL, the request is encoded without a payload.

_nodeid_ affects request routing, and must be set to one of the following
values:

FLUX_NODEID_ANY::
The request is routed to the first matching service instance.

FLUX_NODEID_UPSTREAM::
The request is routed to the first matching service instance,
skipping over the sending rank.

integer::
The request is routed to a specific rank.

_flags_ may be zero or:

FLUX_RPC_NORESPONSE::
No response is expected.  The request will not be assigned a matchtag,
and the returned flux_future_t is immediately fulfilled, and may simply
be destroyed.

FLUX_RPC_STREAMING::
The RPC is for a service that may send zero or more non-error responses,
and a final error response.  ENODATA should be interpreted as a non-error
end-of-stream sentinel.


RESPONSE OPTIONS
----------------

The response message is stored in the future when the future is fulfilled.
At that time it is decoded with `flux_response_decode(3)`.  If it cannot
be decoded, or if the service returned an error, the future is fulfilled
with an error.  Otherwise it is fulfilled with the response message.
If there was an error, `flux_future_get()` or the `flux_rpc_get()` variants
return an error.

`flux_rpc_get()` sets _s_ (if non-NULL) to the NULL-terminated string
payload contained in the RPC response.  If there was no payload, _s_
is set to NULL.

`flux_rpc_get_unpack()` decodes the NULL-terminated string payload as JSON
using Jansson `json_unpack()` style arguments (see below).  It is an error
if there is no payload, or if the payload is not JSON.

`flux_rpc_get_raw()` assigns the raw payload of the RPC response message
to _data_ and its length to _len_.  If there is no payload, this function
will fail.


PREMATURE DESTRUCTION
---------------------

If a regular RPC future is destroyed before its response is received,
the matchtag allocated to it is not immediately returned to the pool
for reuse.  If an unclaimed response subsequently arrives with that
matchtag, it is returned to the pool then.

If a *streaming* RPC future is destroyed before its terminating response
is received, its matchtag is only returned to the pool when an unclaimed
*error* response is received.  Non-error responses are ignored.

It is essential that services which return multiple responses verify that
requests were made with the FLUX_RPC_STREAMING flag and return an immediate
EPROTO error if they were not.  See flux_respond(3).


CANCELLATION
-------------
 
Flux RFC 6 does not currently specify a cancellation protocol for an
individual RPC, but does stipulate that an RPC may be canceled if a disconnect
message is received, as is automatically generated by the local connector
upon client disconnection.


include::JSON_PACK.adoc[]


include::JSON_UNPACK.adoc[]


RETURN VALUE
------------

`flux_rpc()`, `flux_rpc_pack()`, and `flux_rpc_raw()` return a flux_future_t
object on success.  On error, NULL is returned, and errno is set appropriately.

`flux_rpc_get()`, `flux_rpc_get_unpack()`, and `flux_rpc_get_raw()` return
zero on success.  On error, -1 is returned, and errno is set appropriately.


ERRORS
------

ENOSYS::
Service is not available (misspelled topic string, module not loaded, etc),
or flux_t handle has no send operation.

EINVAL::
Some arguments were invalid.

EPROTO::
A request was malformed, the FLUX_RPC_STREAMING flag was
omitted on a request to a service that may send multiple responses,
or other protocol error occurred.


EXAMPLES
--------

This example performs a synchronous RPC with the broker's "attr.get"
service to obtain the broker's rank.

....
include::trpc.c[]
....

This example registers a continuation to do the same thing asynchronously.

....
include::trpc_then.c[]
....


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
---------
flux_future_get(3), flux_respond(3)

https://github.com/flux-framework/rfc/blob/master/spec_6.adoc[RFC 6: Flux
Remote Procedure Call Protocol]
