flux_reduce_create(3)
=====================
:doctype: manpage


NAME
----
flux_reduce_create, flux_reduce_destroy, flux_reduce_append, flux_reduce_pop, flux_reduce_push, flux_reduce_opt_get, flux_reduce_opt_set - low level support for reduction pattern


SYNOPSIS
--------

 #include <flux/core.h>

 struct flux_reduce_ops {
     flux_free_f  destroy;
     void         (*reduce)(flux_reduce_t *r, int batch, void *arg);
     void         (*sink)(flux_reduce_t *r, int batch, void *arg);
     void         (*forward)(flux_reduce_t *r, int batch, void *arg);
     int          (*itemweight)(void *item);
 };

 flux_reduce_t *flux_reduce_create (flux_t h, flux_reduce_ops ops,
                                    double timeout, void *arg, int flags);

 void flux_reduce_destroy (flux_reduce_t *r);

 int flux_reduce_append (flux_reduce_t *r, void *item, int batch);

 void *flux_reduce_pop (flux_reduce_t *r);

 int flux_reduce_push (flux_reduce_t *r, void *item);

 int flux_reduce_opt_get (flux_reduce_t *r, int option,
                          void *val, size_t size);

 int flux_reduce_opt_set (flux_reduce_t *r, int option,
                          void *val, size_t size);


DESCRIPTION
-----------

`flux_reduce_create()` sets up a reduction handle, a queue with semantics
useful for implementing hierarchical reduction patterns over the Flux tree
based overlay network.  It is a "bare bones" interface that requires the
user to provide callbacks via _ops_ to do the work of reducing, forwarding,
and consuming items of an opaque, user-defined type.

Items are appended to the reduction handle with `flux_reduce_append()`
with _batch_, a monotonically increasing sequence number.  Only
items in batches of the same number can be reduced together.  Each time an
item is appended to the handle and two or more items are available there,
the _op.reduce_ callback, if non-NULL, is called.

_op.reduce_ should call `flux_reduce_pop()` to obtain items for the current
_batch_, perform some operation on them, then call `flux_reduce_push()`
to put items back.  The purpose of _op.reduce_ is to consolidate items
so that the amount of data arriving at each node of the tree can be minimized
to improve scalability.

Depending on _flags_, the queue will be flushed periodically.  The flush
operation empties the queue of items in the current batch by calling
_op.forward_ (rank > 0) or  _op.sink_ (rank = 0), if defined, then internally
popping items off and destroying them with _op.destroy_, if defined.

The purpose of _op.forward_ is to forward items "upstream" towards the root
of the tree.  _op.forward_ should call `flux_reduce_pop()` to obtain items,
and encode each of them them in a request message with the batch number.
The request message should be sent upstream with FLUX_NODEID_UPSTREAM
addressing.  The upstream rank, on receipt, should decode the item and
batch number, then call `flux_reduce_append()` to append the item to its
reduction handle.  _op.forward_ is never called on rank zero.

The purpose of _op.sink_ is to consume items in their fully reduced form.
_op.sink_ should call `flux_reduce_pop()` to obtain items.  Depending on
the application and the selected flush policy, _op.sink_ may need to be
prepared to handle late arriving items from a previous batch.
_op.sink_ is only called on rank zero.

_flags_ is the logical "or" of zero or more of the following flags:

FLUX_REDUCE_TIMEDFLUSH::
When an item of a new batch is appended to the reduction handle, a reactor
timer is started on handle _h_ for _timeout_ seconds.  When the timer
expires, any items in the queue are flushed.

FLUX_REDUCE_HWMFLUSH::
A high water mark for the number of messages appended to the handle
is, by default, "learned" on the first batch.  Thereafter, a flush occurs
whenever the high water mark is reached.  The high water mark can be increased
by subsequent batches, but will never decrease.  If this flag is used,
_op.itemweight_ must be provided (see below).

If no flush policy is selected, or during the learning period of
HWMFLUSH policy, the flush is immediate and no reduction can be performed.

If both TIMEDFLUSH and HWMFLUSH policy are selected, the flush will occur
on reaching the high water mark, or timer expiration, whichever occurs first.

If a straggler item from a previously flushed batch is received,
that item is flushed immediately.  During _op.forward_ or _op.sink_
callbacks, `flux_reduce_pop()` will return NULL after the straggler
is popped without co-mingling any items from the current batch.

The high water mark training period counts unreduced messages, while
subsequent high water mark comparisons must count reduced messages.
If HWMFLUSH policy is selected, _op.itemweight_ must be provided
to interrogate an item for the number of unreduced items it represents.

`flux_reduce_opt_get()` and `flux_reduce_opt_set()` may be used to get
or set internal options.  The valid options are:

FLUX_REDUCE_OPT_TIMER::
Get/set the timeout value used for TIMEDFLUSH policy.
The units are seconds and the value type is double.

FLUX_REDUCE_OPT_HWM::
Get/set the internal high water mark used for HWMFLUSH policy.
The units are items and the value type is an unsigned integer.
After the high water mark has been set manually it will not change.

FLUX_REDUCE_OPT_COUNT::
Get the unweighted item count for items queued within the handle.  The
units are items and the value type is an unsigned integer.
This option cannot be set.

FLUX_REDUCE_OPT_WCOUNT::
Get the weighted item count for items queued within the handle.  The
units are items and the value type is an unsigned integer.
This option cannot be set.


RETURN VALUE
------------

`flux_reduce_create()` returns a flux_reduce_t object on success.
On error, NULL is returned, and errno is set appropriately.

`flux_reduce_append()`, `flux_reduce_push()`, `flux_reduce_opt_set()`,
and `flux_reduce_opt_get()` return zero on success.  On error, -1 is
returned, and errno is set appropriately.

`flux_reduce_pop()` returns an item or NULL if there are none.
It does not report errors.


ERRORS
------

EINVAL::
Some arguments were invalid.


EXAMPLES
--------

In this example comms module, an "item" is a string representation of
a nodeset, e.g. "[0-3,5-12]".  On each heartbeat, each rank provides
its rank number as input to the reduction handle.  The reduction consists
of building a nodeset string which is printed on rank 0.  For example,
in a 1024 rank session, each rank provides "0", "1", "2", ..., "1023",
and after the reduction, rank 0 prints "[0-1023]".

If a floating point argument is passed to the module, it is interpreted as
a timeout value, and FLUX_REDUCE_TIMEDFLUSH policy is selected; otherwise,
FLUX_REDUCE_HWMFLUSH policy is selected.

....
include::treduce.c[]
....


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
--------
flux_get_rank(3)
