flux_respond(3)
===============
:doctype: manpage


NAME
----
flux_respond, flux_respond_pack, flux_respond_raw, flux_respond_error - respond to a request


SYNOPSIS
--------
 #include <flux/core.h>

 int flux_respond (flux_t *h, const flux_msg_t *request,
                   const char *s);

 int flux_respond_pack (flux_t *h, const flux_msg_t *request,
                        const char *fmt, ...);

 int flux_respond_raw (flux_t *h, const flux_msg_t *request,
                       int errnum, const void *data, int length);

 int flux_respond_error (flux_t *h, const flux_msg_t *request,
                         int errnum, const char *errmsg);

DESCRIPTION
-----------

`flux_respond()`, `flux_respond_pack()`, `flux_respond_raw()`, and
`flux_respond_error()`  encode and send a response message on handle _h_,
deriving topic string, matchtag, and route stack from the provided
_request_.

`flux_respond()` sends a response to _request_.  If _s_ is non-NULL,
`flux_respond()` will send it as the response payload, otherwise there
will be no payload.

`flux_respond_raw()` is identical except if _data_ is non-NULL,
`flux_respond_raw()` will send it as the response payload.

`flux_respond_pack()` encodes a response message with a JSON payload,
building the payload using variable arguments with a format string in
the style of jansson's `json_pack()` (used internally).

`flux_respond_error()` returns an error response to the sender.
_errnum_ must be non-zero.  If _errmsg_ is non-NULL, an error string
payload is included in the response.  The error string may be used to
provide a more detailed error message than can be conveyed via _errnum_.


STREAMING SERVICES
------------------

Per RFC 6, a "streaming" service must return zero or more non-error
responses to a request and a final error response.  If the requested
operation was successful, the final error response may use ENODATA as
the error number.  Clients should interpret ENODATA as a non-error
end-of-stream marker.

It is essential that services which return multiple responses verify that
requests were made with the FLUX_RPC_STREAMING flag by testing the
FLUX_MSGFLAG_STREAMING flag, e.g. using `flux_msg_is_streaming()`.
If the flag is not set, the service must return an immediate EPROTO error.


include::JSON_PACK.adoc[]


RETURN VALUE
------------

These functions return zero on success.  On error, -1 is returned,
and errno is set appropriately.


ERRORS
------

ENOSYS::
Handle has no send operation.

EINVAL::
Some arguments were invalid.

EPROTO::
A protocol error was encountered.


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
---------
flux_rpc(3), flux_rpc_raw(3)

https://github.com/flux-framework/rfc/blob/master/spec_6.adoc[RFC 6: Flux
Remote Procedure Call Protocol]

https://github.com/flux-framework/rfc/blob/master/spec_3.adoc[RFC 3: CMB1 - Flux Comms Message Broker Protocol]
