flux_rpc(3)
===========
:doctype: manpage


NAME
----
flux_rpc, flux_rpcf, flux_rpc_get, flux_rpc_getf, flux_rpc_destroy - perform a remote procedure call to a Flux service


SYNOPSIS
--------
 #include <flux/core.h>

 flux_rpc_t *flux_rpc (flux_t *h, const char *topic,
                       const char *json_in,
                       uint32_t nodeid_in, int flags);

 flux_rpc_t *flux_rpcf (flux_t *h, const char *topic,
                       uint32_t nodeid_in, int flags,
                       const char *fmt, ...);


 void flux_rpc_destroy (flux_rpc_t *rpc);

 int flux_rpc_get (flux_rpc_t *rpc, const char **json_out);

 int flux_rpc_getf (flux_rpc_t *rpc, const char *fmt, ...);


DESCRIPTION
-----------

`flux_rpc()` encodes and sends a request message, comprising the first
half of a remote procedure call (RPC).  A flux_rpc_t object is returned
which can be passed to `flux_rpc_get()` to obtain the decoded response
message, comprising the second half of the RPC.  The flux_rpc_t should
finally be disposed of using `flux_rpc_destroy()`.

_topic_ must be set to a topic string representing the Flux
service that will handle the request.

_json_in_, if non-NULL, must be a string containing valid serialized
JSON to be attached as payload to the request.  If NULL, the request
will be sent without a payload.

_nodeid_in_ affects request routing, and must be set to one of the following
values:

FLUX_NODEID_ANY::
The request is routed to the first matching service instance.

FLUX_NODEID_UPSTREAM::
The request is routed to the first matching service instance,
skipping over the sending rank.

integer::
The request is routed to a specific rank.

_flags_ may be zero or:

FLUX_RPC_NORESPONSE::
No response is expected.  The request will not be assigned a matchtag,
and the flux_rpc_t returned by `flux_rpc()` may be immediately destroyed.

`flux_rpc_get()` blocks until a matching response is received, then
decodes the result.  For asynchronous response handling, see flux_rpc_then(3).

_json_out_, if non-NULL, is assigned a string containing valid
serialized JSON from the response payload.  If no payload exists,
_json_out_ is set to NULL.  The storage associated with _json_out_
belongs to the flux_rpc_t object and is invalidated when that object
is destroyed.

`flux_rpc_destroy()` destroys a completed `flux_rpc_t`, invalidating 
payload as described above, and freeing the RPC matchtag.  Destroying
an RPC before completion renders the matchtag associated with the RPC
unusable; it is effectively leaked from the matchtag pool.

`flux_rpcf()` is a variant of `flux_rpc()` that constructs a JSON
payload based on the provided _fmt_ string and variable arguments.
The _fmt_ string and variable arguments are passed internally to
jansson's `json_pack()` function.  See below for details.

`flux_rpc_getf()` is a variant of `flux_rpc_get()` that parses a JSON
payload based on the provided _fmt_ string and variable arguments.
The _fmt_ string and variable arguments are passed internally to
jansson's `json_unpack()` function.  Any strings or objects returned
are invalidated when `flux_rpc_destroy()` is called.  See below
for details.


include::JSON_PACK.adoc[]


include::JSON_UNPACK.adoc[]


CANCELLATION
------------

Flux RFC 6 does not currently specify a cancellation protocol for an
individual RPC, but does stipulate that an RPC may be canceled if a disconnect
message is received, as is automatically generated by the local connector
upon client disconnection.

If `flux_rpc_destroy()` is called before a response is received, a
matchtag value from the handle _h_'s matchtag pool is leaked.
If enough matchtags are leaked, it will be impossible to make RPC calls
on that handle.


RETURN VALUE
------------

`flux_rpc()` and `flux_rpcf()` returns a flux_rpc_t object on success.
On error, NULL is returned, and errno is set appropriately.

`flux_rpc_get()` and `flux_rpc_getf()` returns zero on success.  On
error, -1 is returned, and errno is set appropriately.


ERRORS
------

ENOSYS::
Handle has no send operation.

EINVAL::
Some arguments were invalid.

EPROTO::
A protocol error was encountered.


EXAMPLES
--------

This example performs a synchronous RPC with the broker's "cmb.attrget"
service to obtain the broker's rank.

....
include::trpc.c[]
....


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
---------
flux_rpc_then(3)

https://github.com/flux-framework/rfc/blob/master/spec_6.adoc[RFC 6: Flux
Remote Procedure Call Protocol]
