flux_kvs_lookup(3)
==================
:doctype: manpage


NAME
----
flux_kvs_lookup, flux_kvs_lookupat, flux_kvs_lookup_get, flux_kvs_lookup_get_unpack, flux_kvs_lookup_get_raw, flux_kvs_lookup_get_dir, flux_kvs_lookup_get_treeobj, flux_kvs_lookup_get_symlink - look up KVS key


SYNOPSIS
--------
 #include <flux/core.h>

 flux_future_t *flux_kvs_lookup (flux_t *h, int flags, const char *key);

 flux_future_t *flux_kvs_lookupat (flux_t *h, int flags,
                                   const char *key, const char *treeobj);

 int flux_kvs_lookup_get (flux_future_t *f, const char **value);

 int flux_kvs_lookup_get_unpack (flux_future_t *f, const char *fmt, ...);

 int flux_kvs_lookup_get_raw (flux_future_t *f,
                              const void **data, int *len);

 int flux_kvs_lookup_get_dir (flux_future_t *f,
                              const flux_kvsdir_t **dir);

 int flux_kvs_lookup_get_treeobj (flux_future_t *f, const char **treeobj);

 int flux_kvs_lookup_get_symlink (flux_future_t *f, const char **target);

 const char *flux_kvs_lookup_get_key (flux_future_t *f);


DESCRIPTION
-----------

The Flux Key Value Store is a general purpose distributed storage
service used by Flux services.

`flux_kvs_lookup()` sends a request to the KVS service to look up _key_.
It returns a `flux_future_t` object which acts as handle for synchronization
and container for the result.  _flags_ modifies the request as described
below.

`flux_kvs_lookupat()` is identical to `flux_kvs_lookup()` except
_treeobj_ is a serialized RFC 11 object that references a particular
static set of content within the KVS, effectively a snapshot.
See `flux_kvs_lookup_get_treeobj()` below.

By default, both `flux_kvs_lookup()` and `flux_kvs_lookupat()` operate
on the default KVS namespace.  To use a different namespace, see the
`flux_kvs_set_namespace()` function or set the environment variable
FLUX_KVS_NAMESPACE to the namespace you wish to use.

All the functions below are variations on a common theme.  First they
complete the lookup RPC by blocking on the response, if not already received.
Then they interpret the result in different ways.  They may be called more
than once on the same future, and they may be intermixed to probe a result
or interpret it in different ways.  Results remain valid until
`flux_future_destroy()` is called.

`flux_kvs_lookup_get()` interprets the result as a value.  If the value
has length greater than zero, a NULL is appended and it is assigned
to _value_, otherwise NULL is assigned to _value_.

`flux_kvs_lookup_get_unpack()` interprets the result as a value, which
it decodes as JSON according to variable arguments in Jansson
`json_unpack()` format.

`flux_kvs_lookup_get_raw()` interprets the result as a value.  If the value
has length greater than zero, the value and its length are assigned to
_buf_ and _len_, respectively.  Otherwise NULL and zero are assigned.

`flux_kvs_lookup_get_dir()` interprets the result as a directory,
e.g. in response to a lookup with the FLUX_KVS_READDIR flag set.
The directory object is assigned to _dir_.

`flux_kvs_lookup_get_treeobj()` interprets the result as any RFC 11 object.
The object in JSON-encoded form is assigned to _treeobj_.  Since all
lookup requests return an RFC 11 object of one type or another, this
function should work on all.

`flux_kvs_lookup_get_symlink()` interprets the result as a symlink target,
e.g. in response to a lookup with the FLUX_KVS_READLINK flag set.
The result is parsed and symlink target is assigned to _target_.

`flux_kvs_lookup_get_key()` accesses the key argument from the original
lookup.

These functions may be used asynchronously.  See `flux_future_then(3)` for
details.


FLAGS
-----

The following are valid bits in a _flags_ mask passed as an argument
to `flux_kvs_lookup()` or `flux_kvs_lookupat()`.

FLUX_KVS_READDIR::
Look up a directory, not a value.  The lookup fails if the key does
not refer to a directory object.

FLUX_KVS_READLINK::
If key is a symlink, read the link value.  The lookup fails if the key
does not refer to a symlink object.

FLUX_KVS_TREEOBJ::
All KVS lookups return an RFC 11 tree object.  This flag requests that
they be returned without conversion.  That is, a "valref" will not
be converted to a "val" object, and a "dirref" will not be converted
to a "dir" object.  This is useful for obtaining a snapshot reference
that can be passed to `flux_kvs_lookupat()`.


RETURN VALUE
------------

`flux_kvs_lookup()` and `flux_kvs_lookupat()` return a
`flux_future_t` on success, or NULL on failure with errno set appropriately.

`flux_kvs_lookup_get()`, `flux_kvs_lookup_get_unpack()`,
`flux_kvs_lookup_get_raw()`, `flux_kvs_lookup_get_dir()`,
`flux_kvs_lookup_get_treeobj()`, and `flux_kvs_lookup_get_symlink()`
return 0 on success, or -1 on failure with errno set appropriately.

`flux_kvs_lookup_get_key()` returns key on success, or NULL with errno
set to EINVAL if its future argument did not come from a KVS lookup.


ERRORS
------

EINVAL::
One of the arguments was invalid, or FLUX_KVS_READLINK was used but
the key does not refer to a symlink.

ENOMEM::
Out of memory.

ENOENT::
An unknown key was requested.

ENOTDIR::
FLUX_KVS_READDIR flag was set and key does NOT point to a directory.

EISDIR::
FLUX_KVS_READDIR flag was NOT set and key points to a directory.

EPROTO::
A request or response was malformed.

EFBIG::

ENOSYS::
The KVS module is not loaded.

ENOTSUP::
An unknown namespace was requested.

AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
---------
flux_rpc(3), flux_future_then(3), flux_kvs_set_namespace(3)

https://github.com/flux-framework/rfc/blob/master/spec_11.adoc[RFC 11: Key Value Store Tree Object Format v1]
