flux_recv(3)
============
:doctype: manpage


NAME
----
flux_recv - receive message using Flux Message Broker


SYNOPSIS
--------
#include <flux/core.h>

flux_msg_t *flux_recv (flux_t *h, struct flux_match match, int flags);


DESCRIPTION
-----------

`flux_recv()` receives a message using the Flux Message broker,
previously opened with `flux_open()` on handle _h_.
The message should eventually be destroyed with `flux_msg_destroy()`.

_match_ is a message match structure which limits which messages
can be received.
....
struct flux_match {
    int typemask;      // bitmask of matching message types
    uint32_t matchtag; // matchtag
    char *topic_glob;  // glob matching topic string
};
....
The following initializers are available for _match_:

FLUX_MATCH_ANY::
Match any message.

FLUX_MATCH_EVENT::
Match any event message.

For additional details on how to use _match_, see flux_msg_cmp(3).

_flags_ is the logical "or" of zero or more of the following flags:

FLUX_O_TRACE::
Dumps _msg_ to stderr.

FLUX_O_NONBLOCK::
If unable to receive a matching message, return an error rather than block.

Internally, flags are the logical "or" of _flags_ and the flags provided
to `flux_open()` when the handle was created.

Messages that do not meet _match_ criteria, are requeued with
`flux_requeue()` for later consumption, unless the caller is in
coprocess context.  See COPROCESS CONTEXT below.

COPROCESS CONTEXT
-----------------

Reactor message watcher callbacks are started in coprocess context if
the FLUX_O_COPROC flag is set in the handle before `flux_reactor_start()`.
In coprocess context, `flux_recv()` is a _scheduling point_ where other
message watchers are allowed to run as matching messages arrive.

This mode can be useful in a comms module that implements several
service methods, which may in turn make requests of other services.
It preserves a synchronous control flow within the service method,
without stalling other service methods or the reactor.

Coprocess mode should be considered experimental at this point,
so use with care.

RETURN VALUE
------------

`flux_recv()` returns a message on success.  On error, NULL is returned,
and errno is set appropriately.


ERRORS
------

ENOSYS::
Handle has no recv operation.

EINVAL::
Some arguments were invalid.

EAGAIN::
`FLUX_O_NONBLOCK` was selected and `flux_send()` would block.


EXAMPLES
--------

This example opens the Flux broker and displays event messages
as they arrive.

....
include::trecv.c[]
....


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
---------
flux_open(3), flux_send(3), flux_requeue(3), flux_msg_cmp(3)
