flux_kvs_lookup(3)
==================
:doctype: manpage


NAME
----
flux_kvs_lookup, flux_kvs_lookupat, flux_kvs_lookup_get, flux_kvs_lookup_get_unpack - look up KVS key


SYNOPSIS
--------
 #include <flux/core.h>

 flux_future_t *flux_kvs_lookup (flux_t *h, int flags, const char *key);

 flux_future_t *flux_kvs_lookupat (flux_t *h, int flags,
                                   const char *key, const char *treeobj);

 int flux_kvs_lookup_get (flux_future_t *f, const char **json_str);

 int flux_kvs_lookup_get_unpack (flux_future_t *f, const char *fmt, ...);


DESCRIPTION
-----------

The Flux Key Value Store is a general purpose distributed storage
service used by Flux services.  It is (currently) a single namespace
per Flux instance and is available globally, with "loosely consistent"
semantics.

`flux_kvs_lookup()` sends a request to the KVS service to translate
_key_ to its current value.  It returns a `flux_future_t` object which
acts as handle for synchronization and container for the response.
_flags_ modifies the request as described below.

`flux_kvs_lookupat()` is identical to `flux_kvs_lookup()` except
_treeobj_ is a serialized JSON treeobj object that references a
particular snapshot within the KVS.

`flux_kvs_lookup_get ()` completes a lookup operation, blocking on
response(s) if needed, parsing the result, and returning the requested
value in _json_str_.  _buf_ is valid until `flux_future_destroy()` is called.
_json_str_ may be a JSON object, array, or bare value.

`flux_kvs_lookup_get_unpack()` is identical to `flux_kvs_lookup_get()` except
the returned JSON is parsed according to variable arguments in Jansson
`json_unpack()` format.

These functions may be used asynchronously.
See `flux_future_then(3)` for details.


FLAGS
-----

The following are valid bits in a _flags_ mask passed as an argument
to `flux_kvs_lookup()` or `flux_kvs_lookupat()`.

FLUX_KVS_READDIR::
Look up a directory, not a value.  The lookup fails if the key does
not refer to a directory object.

FLUX_KVS_READLINK::
If key is a symlink, read the link value, what it refers to.

FLUX_KVS_TREEOBJ::
Return the object representation.


RETURN VALUE
------------

`flux_kvs_lookup()` and `flux_kvs_lookupat()` return a
`flux_future_t` on success, or NULL on failure with errno set appropriately.

`flux_kvs_lookup_get()` and `flux_kvs_lookup_getat()`
return 0 on success, or -1 on failure with errno set appropriately.


ERRORS
------

EINVAL::
One of the arguments was invalid.

ENOMEM::
Out of memory.

ENOENT::
An unknown key was requested.

ENOTDIR::
FLUX_KVS_READDIR flag was set and key does NOT point to a directory.

EISDIR::
FLUX_KVS_READDIR flag was NOT set and key points to a directory.

EPROTO::
A request was malformed.

EFBIG::

ENOSYS::
The KVS module is not loaded.


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
---------
flux_rpc(3), flux_future_then(3)

https://github.com/flux-framework/rfc/blob/master/spec_11.adoc[RFC 11: Key Value Store Tree Object Format v1]
