flux_msg_sendfd(3)
==================
:doctype: manpage


NAME
----
flux_msg_sendfd, flux_msg_recvfd - send/recv a Flux message by file descriptor


SYNOPSIS
--------
#include <flux/core.h>

int flux_msg_sendfd (int fd, const flux_msg_t *msg,
                     struct flux_msg_iobuf *iobuf);

flux_msg_t *flux_msg_recvfd (int fd, struct flux_msg_iobuf *iobuf);

void flux_msg_iobuf_init (struct flux_msg_iobuf *iobuf);

void flux_msg_iobuf_clean (struct flux_msg_iobuf *iobuf);

DESCRIPTION
-----------

`flux_msg_sendfd()` encodes and sends a message on _fd_.

`flux_msg_recvfd()` receives and decodes a message on _fd_.
The caller must dispose of the returned message with flux_msg_destroy().

If the file descriptor is open in non-blocking mode, _iobuf_ may passed in
to capture intermediate state on internal EWOULDBLOCK or EAGAIN errors.
The function may be called again with identical arguments to continue
the operation once the file descriptor is ready.

_iobuf_ should first be initialized with `flux_msg_iobuf_init()`.

While EWOULDBLOCK or EAGAIN handling is in progress, and only then, _iobuf_
contains internally allocated storage.  If you need to abort an
in-progress call, `flux_msg_iobuf_clean()` should be called to free
this internal storage.  This function is a no-op if there is no storage
allocated.

ENCODING
--------

Message are internally encoded with `flux_msg_encode(3)` and decoded
with `flux_msg_decode(3)`.  In addition, a 4 byte message size is encoded
before the encoded message, in network byte order.

    
RETURN VALUE
------------

`flux_msg_sendfd()` returns 0 on success.  On error, -1 is returned,
and errno is set appropriately.

`flux_msg_recvfd()` returns the decoded message on success.  On error, NULL
is returned, and errno is set appropriately.

ERRORS
------

EINVAL::
Some arguments were invalid.

ENOMEM::
Out of memory.

EAGAIN or EWOULDBLOCK::
See ERRORS in read(2) and write(2).

EPROTO::
Message was malformed; EOF was received on socket; or EWOULDBLOCK, EAGAIN
was internally converted to EPROTO because _iobuf_ was NULL.
After an EPROTO, the file descriptor may not be positioned at a message
boundary, and should not be used.

AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
--------
flux_msg_encode(3)
