#!/usr/bin/env python

import sys, json

from ruamel.yaml import YAML

yaml = YAML(typ='safe')   # default, if not specfied, is 'rt' (round-trip)

obj = yaml.load(sys.stdin)

json.dump(obj, sys.stdout, separators=(',',':'))
