#!/bin/bash -e

# basic put, commit, get test (boolean value)

TEST=`basename $0`
KEY=$TEST.a.b.c

test_cleanup() {
    ../flux kvs --quiet $TEST=
}

kvs() {
    ../flux kvs --no-commit --quiet --null-noerror $*
}

test_cleanup

# read nonexistent key
RESULT=`kvs $KEY`
test "$RESULT" == "null"

# put with no commit should have no effect
kvs $KEY=true
RESULT=`kvs $KEY`
test "$RESULT" == "null"

# put with commit should work
kvs $KEY=true ^
RESULT=`kvs $KEY`
test "$RESULT" == "true"

test_cleanup

exit 0
