#!/bin/bash -e

# check directory semantics

TEST=`basename $0`
KEY=$TEST.a.b.c
DIR=$TEST.a.b

test_cleanup() {
    ../flux kvs --quiet $TEST=
}

kvs() {
    ../flux kvs --no-commit --quiet --null-noerror "$@"
}
kvsdir() {
    ../flux kvsdir --values --recursive "$@"
}

test_cleanup

kvs $KEY=69 ^

# Retrieve directory containing new key
RESULT=`kvsdir $DIR`
test "$RESULT" == "$KEY = 69"

# Try to retrieve key as a directory - should be ENOTDIR
kvsdir $KEY 2>/dev/null && false

# Try to retrieve directory as a object - should be EISDIR
kvs $DIR >/dev/null 2>/dev/null && false

# empty directory remains after key removed
kvs $KEY= ^
RESULT=`kvsdir $DIR`
test -z "$RESULT"

test_cleanup

exit 0
