#!/bin/bash -e

# create a directory, put various keys into it, and retrieve them

TEST=`basename $0`
DIR=$TEST.a.b
EXPRESULT="$DIR.a = 69
$DIR.b = 70
$DIR.c = 3.140000
$DIR.d = \"snerg\"
$DIR.e = true"

test_cleanup() {
    ../flux kvs --quiet $TEST=
}

kvs() {
    ../flux kvs --no-commit --quiet --null-noerror "$@"
}
kvsdir() {
    ../flux kvsdir --values --recursive "$@"
}

test_cleanup

kvs $DIR.a=69 $DIR.b=70 $DIR.c=3.14 $DIR.d=\"snerg\" $DIR.e=true ^

# Retrieve directory containing new keys
RESULT=`kvsdir $DIR | sort`
test "$RESULT" == "$EXPRESULT"

test_cleanup

exit 0
