#!/bin/bash -e

# run multi-threaded test program that modifies a watched key 
# multiple times and verifies that all the threads watching it receive
# the right number of callbacks with the right content

TEST=`basename $0`
KEY=$TEST.a

test_cleanup() {
    ../flux kvs --quiet $TEST=
}

test_cleanup

./tkvswatch 100 100 $KEY

test_cleanup

exit 0
