#!/bin/bash -e

# test symlink resolution when final path component is a symlink

TEST=`basename $0`
KEY=$TEST.a.b.c
KVAL="foo"
KLINK=$TEST.Q

test_cleanup() {
    ../flux kvs --quiet $TEST=
}
kvs() {
    ../flux kvs --no-commit --quiet --null-noerror "$@"
}
kvsdir() {
    ../flux kvsdir --values --recursive "$@"
}
kvssymlink() {
    ../flux kvs --symlink "$1"
}
kvsreadlink() {
    ../flux kvs --quiet --readlink "$1"
}

test_cleanup

kvs $KEY="\"$KVAL\"" ^
kvssymlink $KLINK=$KEY 

# check regular key value 
RESULT=`kvs $KEY`
test "$RESULT" == "\"$KVAL\""

# symlink should have same value as regular key
RESULT=`kvs $KLINK`
test "$RESULT" == "\"$KVAL\""

# read the link value
RESULT=`kvsreadlink $KLINK`
test "$RESULT" == "$KEY"

test_cleanup

exit 0
