#!/bin/bash -e

# Test path resolution when intermediate component is a symlink 
#    and points to a nonexistent key

TEST=`basename $0`

test_cleanup() {
    ../flux kvs --quiet $TEST=
}
kvs() {
    ../flux kvs --no-commit --quiet --null-noerror "$@"
}
kvssymlink() {
    ../flux kvs --symlink "$1"
}

test_cleanup

kvssymlink $TEST.Z.Y=$TEST.a.b

RESULT=`kvs $TEST.Z.Y.c`
test "$RESULT" == "null"

test_cleanup

exit 0
