coverage:
 round: down
 range: "50...100"
 ignore:
 - "t/.*"
 - ".*/test/.*"
 - ".*/tests/.*"
 - ".*/man3/*.c"
 - ".*/common/libtap/.*"
 - ".*/common/liblsd/.*"
 - ".*/common/libev/.*"
 - ".*/common/liboptparse/getopt*"
 - ".*/bindings/python/.*"
 - ".*/common/libutil/sds.*"
 - ".*/common/libminilzo/.*"
 - "/usr/include/.*"
 - "/usr/lib/.*"

comment:
 layout: "header, diff, changes, tree"
