#!/usr/bin/env python
""" List local flux instances.
"""

from __future__ import print_function
import sys, os, re, flux.command_helpers, argparse

parser = argparse.ArgumentParser(description='List local flux instances')

if __name__ == '__main__':
    args = parser.parse_args()
    for sid, uri in flux.command_helpers.list_instances():
        print("{}: {}".format(sid, uri))
