#!/usr/bin/lua
--[[--------------------------------------------------------------------------
 *  Copyright (c) 2016 Lawrence Livermore National Security, LLC.  Produced at
 *  the Lawrence Livermore National Laboratory (cf, AUTHORS, DISCLAIMER.LLNS).
 *  LLNL-CODE-658032 All rights reserved.
 *
 *  This file is part of the Flux resource manager framework.
 *  For details, see https://github.com/flux-framework.
 *
 *  This program is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the Free
 *  Software Foundation; either version 2 of the license, or (at your option)
 *  any later version.
 *
 *  Flux is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the terms and conditions of the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 *  See also:  http://www.gnu.org/licenses/
 ---------------------------------------------------------------------------]]
--
-- Call kvs.setroot with contents of file on cmdline
--
local function load_root_info (path)
    local file = assert (io.open (path))
    local s = file:read ("*all")
    file:close ()
    return assert (loadstring ("return " .. s))()
end

if not arg[1] then
    io.stderr:write ("Usage: "..arg[0].." root-info-file\n")
    os.exit (1)
end

local f, err = require 'flux'.new()
if not f then error (err) end

local kvsroot = load_root_info (arg[1])

print ("Setting root to ".. kvsroot.rootdir)
assert (f:sendevent (kvsroot, "kvs.setroot"))

-- vi: ts=4 sw=4 expandtab
