#!/usr/bin/env lua

-------------------------------------------------------------
-- Copyright 2015 Lawrence Livermore National Security, LLC
-- (c.f. AUTHORS, NOTICE.LLNS, COPYING)
--
-- This file is part of the Flux resource manager framework.
-- For details, see https://github.com/flux-framework.
--
-- SPDX-License-Identifier: LGPL-3.0
-------------------------------------------------------------

--
-- flux-submit: submit jobs using job.submit interface
--
local wreck = require 'wreck' .new ()
if not wreck:parse_cmdline (arg) then
    wreck:die ("Failed to process cmdline args\n")
end

-- If 'nokz' is used without --output, then store stdout and err in
-- well-known kvs keys by default:
if wreck.job_options.nokz and not wreck:getopt('O') then
    wreck.opts.O = "kvs://files.stdout"
    if not wreck:getopt ('E') then wreck.opts.E = "kvs://files.stderr" end

    -- Regenerate wreck.output output file configuration:
    wreck.output = wreck:output_file_config ()
end

local id, err = wreck:submit ()
if not id then wreck:die ("%s\n", err) end
wreck:say ("Submitted jobid %d\n", id)
os.exit (0)
-- vi: ts=4 sw=4 expandtab
