#!/usr/bin/env lua
--[[--------------------------------------------------------------------------
 *  Copyright (c) 2014 Lawrence Livermore National Security, LLC.  Produced at
 *  the Lawrence Livermore National Laboratory (cf, AUTHORS, DISCLAIMER.LLNS).
 *  LLNL-CODE-658032 All rights reserved.
 *
 *  This file is part of the Flux resource manager framework.
 *  For details, see https://github.com/flux-framework.
 *
 *  This program is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the Free
 *  Software Foundation; either version 2 of the license, or (at your option)
 *  any later version.
 *
 *  Flux is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the terms and conditions of the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 *  See also:  http://www.gnu.org/licenses/
 ---------------------------------------------------------------------------]]
--
-- flux-wreck: simple wreck job utility
--
local f, err = require 'flux' .new()
local wreck = require 'wreck'
local hostlist = require 'flux.hostlist'
local posix = require 'posix'
local prog = require 'flux.Subcommander'.create {
    usage = "COMMAND [OPTIONS]",
    handler = function (self, arg)
        self:log ("COMMAND required\n")
        self:help (1)
    end
}

local function printf (...)
    io.stdout:write (string.format (...))
end

local function check_jobid_arg (self, id)
    if not id then
        io.stderr:write ("Error: Job id required\n")
        self:help (1)
    elseif not tonumber (id) then
        self:die ("Invalid Job id '%s'\n", id)
    end
    return id
end


local function kvs_path (id, fmt, ...)
    local p = assert (wreck.id_to_path { flux = f, jobid = id })
    if fmt then
        p = p .. "." .. string.format (fmt, ...)
    end
    return p
end


prog:SubCommand {
 name = "attach",
 description = "Attach to running or completed job output",
 usage = "[OPTIONS] JOBID",
 options = {
     { name = "status",  char = "s",
       usage = "Include status after all output" },
     { name = "label-io",  char = "l",
       usage = "Label lines of output with task id" },
 },
 handler = function (self, arg)
    local id = check_jobid_arg (self, arg[1])
    local state = f:kvs_get (kvs_path (id, "state"))
    local taskio, err = wreck.ioattach {
        flux = f,
        jobid = id,
        labelio = self.opt.l,
        on_completion = function ()
            f:reactor_stop()
        end
    }
    if not taskio then
        self:die ("Failed to connect to job %d: %s\n", id, err)
    end
    if state ~= "complete" and state ~= "reaped" then
        local kz, err = f:kz_open (kvs_path (id, "input.files.stdin"), "w")
        if kz then
            local iow, err = f:iowatcher {
                fd = posix.fileno (io.input()),
                handler = function (iow, r)
                    if r.data then kz:write (r.data) end
                    if r.eof  then kz:close () end
                end
            }
            if not iow then self:die ("error opening stdin: %s\n", err) end
        end
    end
    if not taskio:complete() then f:reactor () end
    if self.opt.s then
        self.parent:run {"status", id}
    end
    os.exit (0)
 end
}

local function opt_sig (s)
    if not s then return posix.SIGTERM end
    if tonumber (s) then return tonumber (s) end
    if not tonumber (posix[s]) then
        prog:die ("Invalid signal '%s'\n", s)
    end
    return tonumber (posix [s])
end

prog:SubCommand {
 name = "kill",
 description = "Kill a running job",
 usage = "[OPTIONS] JOBID",
 options = {
     { name = "signal",  char = "s", arg = "N",
       usage = "Specify signal number N to be sent." }
 },
 handler = function (self, arg)
    local id = check_jobid_arg (self, arg[1])
    local lwj, err = f:kvsdir (kvs_path (id))
    if not lwj then self:die ("Job %d: %s\n", id, err) end
    if lwj.state ~= "running" then
        io.stderr:write ("Job "..id..": "..lwj.state.."\n")
        os.exit (1)
    end
    local sig = opt_sig (self.opt.s)
    local rc, err = f:sendevent ({signal = sig}, "wreck.%d.kill", id)
    if not rc then self:die ("signal: %s\n", err) end
 end
}

prog:SubCommand {
 name = "status",
 description = "Return status of jobs",
 usage = "JOBID",
 handler = function (self, arg)
    local jobid = check_jobid_arg (self, arg[1])
    local lwj, err = f:kvsdir (kvs_path (jobid))
    if not lwj then self:die ("Job %d: %s\n", jobid, err) end
    print ("Job "..jobid.." status: "..lwj.state)
    local code, msglist = wreck.status { flux = f, jobid = jobid }
    if not code then self:die (msglist) end
    for msg, hl in pairs (msglist) do
        local s = string.format ("task%s: %s", tostring (hl:sort()), msg)
        print (s)
    end
    os.exit (code)
 end
}


local LWJ = {}
function LWJ.open (f, id, kvspath)
    if not f or not id then
        return nil, "Required arg missing"
    end
    if not kvspath then
        kvspath = kvs_path (id)
    end
    local lwj, err = f:kvsdir (kvspath)
    if not lwj then
        return nil, "Failed to get lwj info: "..err
    end
    return setmetatable ({id = id, lwj = lwj }, LWJ)
end

local function gettimeofday_as_table ()
    local ts, us = require 'flux.posix'.gettimeofday ()
    if not ts then return nil, us end
    if type (ts) == "table" then return ts end
    return { sec = ts, usec = us }
end

local function now ()
    local t, err = gettimeofday_as_table ()
    if not t then error ("gettimeofday: "..err) end
    return t.sec + (t.usec / (1000 * 1000))
end

function LWJ:timediff (tstart, tend, talt)
    local t0 = self.lwj[tstart.."-time"]
    if not t0 then return 0 end
    local t1 = self.lwj[tend.."-time"]
    if not t1 then t1 = self.lwj[talt.."-time"] end
    if not t1 then t1 = now () end
    local s = t1 - t0
    return s > 0 and s or 0
end

LWJ.__index = function (self, key)
    if key == "state" then
        return self.lwj.state
    elseif key == "ranks" then
        local hl = hostlist.new()
        local rank = self.lwj.rank
        if not rank then return nil end
        for i in rank:keys() do hl:concat (i) end
        return hl:sort()
    elseif key == "ntasks" then
        return self.lwj.ntasks
    elseif key == "nnodes" then
        return self.lwj.nnodes
    elseif key == "runtime" then
        return self:timediff ("starting", "complete", "failed")
    elseif key == "t0" then
        return self:timediff ("create", "starting", "failed")
    elseif key == "t1" then
        return self:timediff ("starting", "running", "failed")
    elseif key == "t2" then
        return self:timediff ("running", "complete", "failed")
    elseif key == "start" then
        return os.date ("%FT%T", self.lwj["starting-time"])
    elseif key == "end" then
        return os.date ("%FT%T", self.lwj["complete-time"])
    elseif key == "created" then
        return os.date ("%FT%T", self.lwj["create-time"])
    elseif key == "command" then
        return self.lwj.cmdline[1]
    end
    return LWJ [key]
end

local function seconds_to_string (s)
    local f = string.format
    if s > (60*60*24) then
        return f ("%.03fd", s / (60*60*24))
    elseif s > (60*60) then
        return f ("%.03fh", s / (60*60))
    elseif s > 60 then
        return f ("%.03fm", s / 60)
    end
    return f ("%.03fs", s)
end

prog:SubCommand {
 name = "ls",
 usage = "",
 description = "List jobs in kvs",
 handler = function (self, arg)
    local dirs = wreck.joblist{ flux = f }
    local fmt = "%6s %6s %-9s %20s %12s %8s %-.13s\n";
    printf (fmt, "ID", "NTASKS", "STATE", "START", "RUNTIME", "RANKS", "COMMAND")
    for _,dir in pairs (dirs) do
        local id = dir:match ("(%d+)$")
        if tonumber (id) then
            local j, err = LWJ.open (f, id, dir)
            if not j then self:die ("job%d: %s", id, err) end
            printf (fmt, id, j.ntasks, j.state, j.start,
                    seconds_to_string (j.runtime),
                    tostring (j.ranks),
                    j.command:match ("([^/]+)$"))
        end
    end
 end
}

prog:SubCommand {
 name = "timing",
 usage = "",
 description = "List timings of jobs in kvs",
 handler = function (self, arg) 
    local dirs = wreck.joblist{ flux = f }
    local fmt = "%6s %12s %12s %12s %12s %12s\n"
    printf (fmt, "ID", "NTASKS", "STARTING", "RUNNING", "COMPLETE", "TOTAL")
    for _,dir in pairs (dirs) do
        local id = dir:match ("(%d+)$")
        if tonumber (id) then
            local j, err = LWJ.open (f, id, dir)
            if not j then self:die ("job%d: %s", id, err) end
            printf (fmt, id,
                    j.ntasks,
                    seconds_to_string (j.t0),
                    seconds_to_string (j.t1),
                    seconds_to_string (j.t2),
                    seconds_to_string (j.runtime))
        end
    end
 end
}

prog:SubCommand {
 name = "kvs-path",
 usage = "ID",
 description = "Display path in KVS to job ID",
 handler = function (self, arg)
    if not arg[1] then self:die ("Job ID argument required\n") end
    print (kvs_path (arg[1]))
 end
}

prog:SubCommand {
 name = "last-jobid",
 description = "Display the last jobid in lwj id sequence",
 usage = "[OPTIONS]",
 options = {
  { name = "kvs-path", char = 'p',
    usage = "Return path to job in kvs instead of jobid",
  }
 },
 handler = function (self, arg)
    local req = {
       name = "lwj",
       preincrement = 0,
       postincrement = 0,
       create = false
    }
    local resp, err = f:rpc ("cmb.seq.fetch", req)
    if not resp then
        self:die ("No last jobid found: %s", err)
    end
    local result = resp.value
    if self.opt.p then
        result = kvs_path (result)
    end
    print (result)
 end
}

prog:SubCommand {
 name = "purge",
 usage = "[OPTIONS]",
 options = {
  { name = "verbose",  char = "v",
    usage = "Increase verbosity." },
  { name = "target-size", char = 't', arg = "N",
    usage = "Specify a target number of lwj entries to keep"
  },
  { name = "remove",  char = "R",
    usage = "Remove all eligible lwj entries." },
  { name = "max",  char = "m", arg = "N",
    usage = "Maximum number of entries to target." },
  { name = "keep", char = "k", arg = "CODE",
    usage = "Keep entries where CODE is true" },
 },
 description = "Purge old jobs entries from kvs",
 handler = function (self, arg)
    local tt = require 'flux.timer'. new()
    local verbose = self.opt.v

    ---
    -- Gather LWJ path list
    --
    local dirs = wreck.joblist{ flux = f }
    if verbose then
        self:log ("%4.03fs: got lwj list (%d entries)\n", tt:get0(), #dirs)
    end

    local total = #dirs
    local target = tonumber (self.opt.t)
    local max = tonumber (self.opt.m) or math.huge
    local keep = function (id) return false end
    if self.opt.k then
        local err
        keep, err =
            loadstring ('local id = tonumber (...); return '..self.opt.k)
        if not keep then
            self:die ("Failed to compile --keep option: %s\n", err)
        end
    end

    -- Without --target-size option, just list current number of lwj entries
    if not target then
        self:log ("%d total job entries\n", total)
    elseif total <= target then
        -- If current total is less than target, then log and exit
        self:log ("%d total jobs at or below target size of %d\n",
                  total, target)
    else
        -- Otherwise, we need to purge some entries:
        --
        local n = math.min (total - target, max)

        -- Remove the first n ids using lwj-completed directory
        local r = {}
        (function() -- anonymous function used for early return
            local completed = f:kvsdir ("lwj-complete")
            for hb in completed:keys () do
                local hb_unlink = true
                local d = completed [hb]
                for id in d:keys() do
                    -- Save name of this kvs path:
                    local complink = tostring (d).."."..id
                    if keep (id) then
                        hb_unlink = false
                    else
                        table.insert (r, id)
                        if self.opt.R then
                            local t, target = f:kvs_type (complink)
                            if t == "symlink" then
                                f:kvs_unlink (target)
                            end
                            f:kvs_unlink (complink)
                        end
                        n = n - 1
                        if n == 0 then return end
                    end
                end
                --
                -- Finished iterating all entries in this hb subdir,
                --  should be ok to remove the hb dir now:
                if self.opt.R and hb_unlink then
                    f:kvs_unlink ("lwj-complete."..hb)
                end
            end
        end)()

        -- gather ids to remove in hostlist for condensed output:
        --
        local hl = require 'flux.hostlist' .new (table.concat (r, ",")):uniq ()
        if self.opt.R then
            f:commit()
            if verbose then
                self:log ("%4.03fs: unlinked %d entries\n", tt:get0(), #hl)
            end
        elseif verbose then
            self:log ("%4.03fs: finished walking %d entries in lwj-complete\n",
                      tt:get0(), #hl)
        end

        local idstring = ""
        if #hl > 0 then
            idstring = ": "..tostring (hl):match ("%[?([^]]+)%]?")
        end
        self:log ("%s %d lwj entries%s\n",
                  self.opt.R and "removed" or "would remove", #hl,
                  idstring)
        if verbose then
            self:log ("%4.03fs: all done.\n", tt:get0());
        end
    end
 end
}


-- Check for valid connection to flux:
if not f then prog:die ("Connecting to flux failed: %s\n", err) end

-- Process cmdline, run any subcommand, or exit with failure:
prog:run (arg)
--  vi: ts=4 sw=4 expandtab
