#!/usr/bin/env lua
--[[--------------------------------------------------------------------------
 *  Copyright (c) 2015 Lawrence Livermore National Security, LLC.  Produced at
 *  the Lawrence Livermore National Laboratory (cf, AUTHORS, DISCLAIMER.LLNS).
 *  LLNL-CODE-658032 All rights reserved.
 *
 *  This file is part of the Flux resource manager framework.
 *  For details, see https://github.com/flux-framework.
 *
 *  This program is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the Free
 *  Software Foundation; either version 2 of the license, or (at your option)
 *  any later version.
 *
 *  Flux is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the IMPLIED WARRANTY OF MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the terms and conditions of the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 *  See also:  http://www.gnu.org/licenses/
 ---------------------------------------------------------------------------]]
--
-- flux-submit: submit jobs using job.submit interface
--
local wreck = require 'wreck' .new ()
if not wreck:parse_cmdline (arg) then
    wreck:die ("Failed to process cmdline args\n")
end

-- If 'nokz' is used without --output, then store stdout and err in
-- well-known kvs keys by default:
if wreck.job_options.nokz and not wreck:getopt('O') then
    wreck.opts.O = "kvs://files.stdout"
    if not wreck:getopt ('E') then wreck.opts.E = "kvs://files.stderr" end

    -- Regenerate wreck.output output file configuration:
    wreck.output = wreck:output_file_config ()
end

local id, err = wreck:submit ()
if not id then wreck:die ("%s\n", err) end
wreck:say ("Submitted jobid %d\n", id)
os.exit (0)
-- vi: ts=4 sw=4 expandtab
