#!/bin/bash -e

# basic put, commit, get test (integer value)

TEST=`basename $0`
KEY=$TEST.a.b.c

test_cleanup() {
    ../flux kvs --quiet $TEST=
}

kvs() {
    ../flux kvs --no-commit --quiet --null-noerror $*
}

test_cleanup

# read nonexistent key
RESULT=`kvs $KEY`
test "$RESULT" == "null"

# put with no commit should have no effect
kvs $KEY=42
RESULT=`kvs $KEY`
test "$RESULT" == "null"

# put with commit should work
kvs $KEY=43 ^
RESULT=`kvs $KEY` 
test "$RESULT" == "43"

test_cleanup

exit 0
