#!/bin/bash -e

TEST=`basename $0`
KEY=$TEST.a.b.c

test_cleanup() {
    ./tkvs unlink $TEST
    ./tkvs commit
}

test_cleanup

RESULT=`./tkvs get_boolean $KEY`
test "$RESULT" == "null"

./tkvs put_boolean $KEY true
RESULT=`./tkvs get_boolean $KEY`
test "$RESULT" == "null"

./tkvs commit
RESULT=`./tkvs get_boolean $KEY` 
test "$RESULT" == "true"

test_cleanup

exit 0
