#!/bin/bash -e

TEST=`basename $0`
KEY=$TEST.a.b.c

test_cleanup() {
    ./tkvs unlink $TEST
    ./tkvs commit
}

test_cleanup

./tkvs mkdir $KEY
./tkvs commit
RESULT=`./tkvs get_dir $KEY`
test -z "$RESULT"

test_cleanup

exit 0
