#!/bin/bash -e

# check that empty directory can be created

TEST=`basename $0`
KEY=$TEST.a.b.c

test_cleanup() {
    ../flux kvs --quiet $TEST=
}

kvsdir() {
    ../flux kvsdir --values --recursive "$@"
}
kvsmkdir() {
    ../flux kvs --mkdir $1
}

test_cleanup

kvsmkdir $KEY
RESULT=`kvsdir $KEY`
test -z "$RESULT"

test_cleanup

exit 0
