#!/bin/bash -e

TEST=`basename $0`
DIR=$TEST.a.b
EXPRESULT="$DIR.a = 69
$DIR.b = 70
$DIR.c = 3.140000
$DIR.d = snerg
$DIR.e = true
$DIR.f.g.h.i.j = blorg"

test_cleanup() {
    ./tkvs unlink $TEST
    ./tkvs commit
}

test_cleanup

./tkvs put_int $DIR.a 69
./tkvs put_int64 $DIR.b 70
./tkvs put_double $DIR.c 3.14
./tkvs put_string $DIR.d "snerg"
./tkvs put_boolean $DIR.e "true"
./tkvs put_string $DIR.f.g.h.i.j "blorg"
./tkvs commit

# Retrieve directory containing new key
RESULT=`./tkvs get_all_r $DIR`

test_cleanup

exit 0
