#!/bin/bash -e

# Test path resolution when intermediate component is a symlink 
#    and points to another symlink

TEST=`basename $0`

test_cleanup() {
    ../flux kvs --quiet $TEST=
}
kvs() {
    ../flux kvs --no-commit --quiet --null-noerror "$@"
}
kvssymlink() {
    ../flux kvs --symlink "$1"
}

test_cleanup

kvs $TEST.a.b.c=42 ^
kvssymlink $TEST.Z.Y=$TEST.a.b
kvssymlink $TEST.X.W=$TEST.Z.Y

RESULT=`kvs $TEST.X.W.c`
test "$RESULT" == "42"

test_cleanup

exit 0
