#!/bin/bash -e

# Test path resolution when intermediate component is a symlink to a symlink
#    and we're doing a readlink

TEST=`basename $0`

test_cleanup() {
    ../flux kvs --quiet $TEST=
}
kvs() {
    ../flux kvs --no-commit --quiet --null-noerror "$@"
}
kvsdir() {
    ../flux kvsdir --values --recursive "$@"
}
kvssymlink() {
    ../flux kvs --symlink "$1"
}
kvsreadlink() {
    ../flux kvs --quiet --readlink "$1"
}

test_cleanup

kvssymlink $TEST.a.b.c="$TEST.dangle"
kvssymlink $TEST.X.Y=$TEST.a.b
kvssymlink $TEST.V.W=$TEST.X.Y

RESULT=`kvsreadlink $TEST.V.W.c`
test "$RESULT" == "$TEST.dangle"

test_cleanup

exit 0
