#!/bin/bash -e

# Test get_version/wait_version

TEST=`basename $0`

test_cleanup() {
    ../flux kvs --quiet $TEST=
}
kvs() {
    ../flux kvs --no-commit --quiet --null-noerror "$@"
}
kvsgetv() {
    ../flux kvs --get-version
}
kvswaitv() {
    ../flux kvs --wait-version=$1
}

test_cleanup

VERS=`kvsgetv`
kvswaitv $(($VERS + 2)) &
kvs foo=42 ^
kvs foo2=43 ^
wait

test_cleanup

exit 0
