#!/bin/bash -e

TEST=`basename $0`
DIR=$TEST.a.b

test_cleanup() {
    ./tkvs unlink $TEST
    ./tkvs commit
}

test_cleanup

./tkvs put_string $DIR.f.g.h.i.j "blorg"
./tkvs commit

RESULT=`./tkvs get_string $DIR.f.g.h.i.j`
test "$RESULT" == "blorg"

RESULT=`./tkvs -c $DIR get_string f.g.h.i.j`
test "$RESULT" == "blorg"

test_cleanup

exit 0
