#!/bin/bash -e

# KVS torture test (small values)

TEST=`basename $0`

test_cleanup() {
    ../flux kvs --quiet $TEST=
}

test_cleanup

../flux kvstorture --quiet --prefix=$TEST

test_cleanup

exit 0
