#!/bin/bash -e

# KVS torture test (large values)

TEST=`basename $0`

test_cleanup() {
    ../flux kvs --quiet $TEST=
}

test_cleanup

../flux kvstorture --size 1024 --quiet --prefix=$TEST

test_cleanup

exit 0
