#!/bin/bash -e

# FIXME: this test is effectively disabled with the '|| true's appended below
# Check that puts of the same value don't increase the size of the store

TEST=`basename $0`

test_cleanup() {
    ../flux kvs --quiet $TEST=
}

kvs() {
    ../flux kvs --no-commit --quiet --null-noerror $*
}

# 13*79 = 1027 byte string
put_longstring() {
    ../flux kvs --quiet $TEST.longstring="\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
"
}

# Get total number of stored objects
get_objcount() {
    ../flux stats --type int --parse 'obj size (KiB)'.'count' kvs
}

# Get total size of stored objects in bytes
get_objsize() {
    ../flux stats --type int --scale 1048576 --parse 'obj size total (MiB)' kvs
}

test_cleanup

# Write/commit value once and get object count
put_longstring
n1=$(get_objcount)
t1=$(get_objsize)

# Write/commit the same thing again and get the object count
put_longstring
n2=$(get_objcount)
t2=$(get_objsize)

n=$(($n2 - $n1))
t=$(($t2 - $t1))

# XXX FIXME: this test is too sensitive and needs to be rethought - DISABLED
# FIXME: eventually this should be zero
# echo "redundant put added $n objects and $t bytes to KVS store"
test $n == 1 || true
test $t -gt 350 && test $t -lt 400 || true

# test_cleanup

exit 0


