#!/bin/bash -e

# start 100 API threads on separate flux_t handles, each doing 50
# (put, fence)'s in a tight loop

TEST=`basename $0`

test_cleanup() {
    ../flux kvs --quiet $TEST=
}

kvs() {
    ../flux kvs --no-commit --quiet --null-noerror $*
}

test_cleanup

./tcommit --fence 100 50 $TEST

test_cleanup

exit 0


