#!/bin/bash

NJOBS=${NJOBS:-10}

flux jobspec srun /bin/true > job.json
for i in `seq 1 $NJOBS`; do
    id[$i]=$(flux job submit < job.json)
    echo ${id[$i]} submitted
done
for i in `seq 1 $NJOBS`; do
    flux job attach ${id[$i]}
    echo ${id[$i]} complete
done
