#!/usr/bin/env bash

set -ex

# Test job wait

id=$(flux submit --flags waitable true)
flux job wait ${id}

# No leaks if zombie persists
id=$(flux submit --flags waitable true)
flux job wait-event ${id} clean
