###############################################################
# Copyright 2014 Lawrence Livermore National Security, LLC
# (c.f. AUTHORS, NOTICE.LLNS, COPYING)
#
# This file is part of the Flux resource manager framework.
# For details, see https://github.com/flux-framework.
#
# SPDX-License-Identifier: LGPL-3.0
###############################################################

"""
Flux interface wrapper generator.
This could, in principle, be used for other projects as well, but it encodes a
number of assumptions about the error propagation and handling that flux uses.

If you add a .so type to be used it, it will be generated by _flux/codegen.py
and the Makefile.am generation needs to be updated appropriately.
"""
from .base import FunctionWrapper, Wrapper, WrapperPimpl  # noqa
from .core import CoreWrapper  # noqa
from .hostlist import HostlistWrapper  # noqa
from .idset import IdsetWrapper  # noqa
