flux-broker-attributes(7)
=========================
:doctype: manpage


NAME
----
flux-broker-attributes - overview Flux broker attributes


DESCRIPTION
-----------

Flux broker attributes are parameters that affect how different
broker systems behave.  Attributes can be listed and manipulated
with flux-getattr(1), flux-setattr(1), and flux-lsattr(1).

The broker currently exports the following attributes:

SESSION ATTRIBUTES
------------------

rank::
The rank of the local broker.

size::
The number of ranks in the comms session.

session-id::
The identity of the comms session.

broker.rundir::
A temporary directory available for scratch storage within
the session.  This directory is unique to the local rank.
Cleanup of directory contents is the responsibility of
the creator.

persist-directory::
A persistent directory available for storage on rank 0 only.
If persist-directory is not defined, persistence is unavailable
and users should fall back to broker.rundir, with cleanup.

persist-filesystem::
If defined, and persist-directory is not defined, the rank
0 broker chooses a unique name for persist-directory within
persist-filesystem and creates it automatically.


TOPOLOGY ATTRIBUTES
-------------------
tbon.arity::
Branching factor of the tree based overlay network.

tbon.descendants::
Number of descendants "below" this node of the tree based
overlay network, not including this node.

tbon.level::
The level of this node in the tree based overlay network.
Root is level 0.

tbon.maxlevel::
The maximum level number in the tree based overlay network.
Maxlevel is 0 for a size=1 instance.

tbon.endpoint::
The endpoint for the tree based overlay network to communicate over.
Format specifier "%h" can be used to specify the IP address of the
host and is useful when configuring an IP endpoint.  Format specifier
"%B" can be used to specify the value of the attribute broker.rundir.
It is useful when configuring an IPC endpoint.  Defaults to
"tcp://%h:*".

mcast.endpoint::
The endpoint for multicast events to be distributed over.  The same
format specifiers can be used as tbon.endpoint.  Special case string
"tbon" can be used to specify that events should instead by
distributed over the tree based overlay network.  Defaults to "tbon".

SOCKET ATTRIBUTES
-----------------

tbon.parent-endpoint::
The URI of the ZeroMQ endpoint this rank is connected to in the tree
based overlay network.  This attribute will not be set on rank zero.

mcast.relay-endpoint::
The URI of the ZeroMQ endpoint this rank is bound to for relay of
multicast messages if multiple ranks are spawned per node.

local-uri::
The Flux URI that should be passed to flux_open(1) to establish
a connection to the local broker rank.

parent-uri::
The Flux URI that should be passed to flux_open(1) to establish
a connection to the enclosing instance.


LOGGING ATTRIBUTES
------------------

log-ring-used::
The number of log entries currently stored in the ring buffer.

log-ring-size::
The maximum number of log entries that can be stored in the ring buffer.

log-count::
The number of log entries ever stored in the ring buffer.

log-forward-level::
Log entries at syslog(3) level at or below this value are forwarded
to rank zero for permanent capture.

log-critical-level::
Log entries at syslog(3) level at or below this value are copied
to stderr on the logging rank, for capture by the enclosing instance.

log-filename::
(rank zero only) If set, session log entries, as filtered by log-forward-level,
are directed to this file.  If unset, but persist-directory is set, log
entries are directed to persist-directory/log.

log-stderr-level::
(rank zero only) Session log entries at syslog(3) level at or below this
value, and as filtered by log-forward-level, are copied to stderr of the
rank zero broker.

log-level::
Log entries at syslog(3) level at or below this value are stored
in the ring buffer.


CONTENT ATTRIBUTES
------------------
content-acct-dirty::
The number of dirty cache entries on this rank.

content-acct-entries::
The total number of cache entries on this rank.

content-acct-size::
The estimated total size in bytes consumed by cache entries on
this rank, excluding overhead.

content-acct-valid::
The number of valid cache entries on this rank.

content-backing::
The selected backing store, if any.  This attribute is only
set on rank 0 where the content backing store is active.

content-blob-size-limit::
The maximum size of a blob, the basic unit of content storage.

content-flush-batch-count::
The current number of outstanding store requests, either to the
backing store (rank 0) or upstream (rank > 0).

content-flush-batch-limit::
The maximum number of outstanding store requests that will be
initiated when handling a flush or backing store load operation.

content-hash::
The selected hash algorithm, default sha1.

content-purge-large-entry::
When the cache size footprint needs to be reduced, first consider
purging entries of this size or greater.

content-purge-old-entry::
When the cache size footprint needs to be reduced, only consider
purging entries that are older than this number of heartbeats.

content-purge-target-entries::
If possible, the cache size purged periodically so that the total
number of entries stays at or below this value.

content-purge-target-size::
If possible, the cache size purged periodically so that the total
size of the cache stays at or below this value.


WIREUP ATTRIBUTES
-----------------
hello.timeout::
The reduction timeout (in seconds) for the broker wireup protocol.
Before the timeout, a topology-based high water mark is applied
at each node of the tree based overlay network.  After the timeout,
new wireup information is forwarded upstream without delay.
Set to 0 to disable the timeout.

hello.hwm::
The reduction high water mark for the broker wireup protocol,
normally calculated based on the topology.
Set to 0 to disable the high water mark.

AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
--------
flux-getattr(1), flux_attr_get(3)
