#!/bin/bash

pepe=../pepe/pepe-launcher
conf=flat
nnodes=
cmd=/bin/bash

usage ()
{
    echo "launch [-n nnodes] [-c config]" >&2
    exit 1
}

while getopts "?hn:c:" opt; do
    case ${opt} in
        h|\?) usage ;;
        n) nnodes=${OPTARG} ;;
        c) conf=${OPTARG} ;;
    esac
done
confpath="./pepe_${conf}.lua"
test -n "$nnodes" || usage
test -f "$confpath" || usage

ulimit -c unlimited
salloc -N$nnodes srun --propagate=CORE \
                      -N$nnodes -n$nnodes --pty $pepe -c $confpath $cmd

# vi:tabstop=4 shiftwidth=4 expandtab
