#!/bin/bash -e

flux module load content-sqlite
flux module load kvs
flux exec -r all -x 0 flux module load kvs
flux exec -r all flux module load aggregator
flux hwloc reload & pids="$pids $!"

flux exec -r all flux module load job-ingest & pids="$pids $!"
flux exec -r all flux module load kvs-watch & pids="$pids $!"
flux exec -r all flux module load job-info & pids="$pids $!"
flux exec -r all flux module load barrier & pids="$pids $!"

wait $pids

flux module load job-manager
flux module load job-exec

flux module load sched-simple
