#!/bin/bash -e

pids=""

flux module load -r 0  content-sqlite
flux module load -r 0 kvs
flux module load -r all -x 0 kvs

flux module load -r all barrier
flux module load -r all aggregator
flux module load -r all job
