#!/bin/bash -e

# t0014-runlevel.t loads this to verify the rc1 environment

# Check that stdio is logged appropriately
echo stderr-1 >&2
echo stderr-2 >&2
echo stdout-1
echo stdout-2

# These are explicitly unset in all rc subprocess environments
# since Flux doesn't yet support simple v1 PMI in jobs that it runs.
if test -n "$PMI_FD" || test -n "$PMI_RANK" || test -n "$PMI_SIZE"; then
    echo "simple v1 PMI variables are set but they should not be" >&2
    exit 1
else
    echo "simple v1 PMI variables are not set"
fi

# We need this to talk to broker
if ! test -n "$FLUX_URI"; then
    echo "FLUX_URI is not set" >&2
    exit 1
else
    echo "FLUX_URI is set"
fi

# Run level should be 1 (and we can talk to broker)
runlevel=$(flux getattr init.run-level)
if test $runlevel -ne 1; then
    echo "run level is $runlevel not 1" >&2
    exit 1
else
    echo "run level is 1"
fi
