#!/bin/bash -e

RANK=$(flux getattr rank)

# Usage: modrm {all|<rank>} modname
modrm() {
    local where=$1; shift
    if test "$where" = "all" || test $where -eq $RANK; then
        flux module remove -f $*
    fi
}


modrm all heartbeat
modrm all kvs-watch
modrm all kvs

flux content flush
modrm 0 content-sqlite
modrm all content
