#!/bin/bash -e

flux module remove -f job-exec
flux module remove -f sched-simple
flux module remove -f resource
flux module remove -f job-manager
flux module remove -f barrier
flux module remove -f job-info
flux module remove -f kvs-watch
flux module remove -f job-ingest
flux module remove -f kvs
flux module remove -f content-sqlite
