#!/bin/bash -e

flux module remove job-manager
flux exec -r all flux module remove job-info
flux exec -r all flux module remove kvs-watch
flux exec -r all flux module remove job-ingest

flux exec -r all -x 0 flux module remove kvs
flux module remove kvs
flux module remove content-sqlite
