#!/bin/bash

pepe=../pepe/pepe-launcher
conf=flat
nnodes=
partition="pdebug"
PTY="--pty"

usage ()
{
    echo "launch [-n nnodes] [-p partition] [-c config]" >&2
    exit 1
}

while getopts ":hbn:c:p:" opt; do
    case ${opt} in
        \?) break;;
        h) usage ;;
        n) nnodes=${OPTARG};;
        p) partition=${OPTARG};;
        c) conf=${OPTARG};;
        b) PTY=;;
    esac
done

#
#  Set command to execute to remainder of cmdline:
#
ARGS=( ${@:$OPTIND} )
if test ${#ARGS[@]} -eq 0; then
   set /bin/bash
else
   set "${ARGS[@]}"
fi

confpath="./pepe/${conf}.lua"
test -f "$confpath" || usage

ulimit -c unlimited

if [ -n "$SLURM_NNODES" ]; then
    srun --propagate=CORE -N${nnodes:-$SLURM_NNODES} ${PTY} $pepe -c $confpath -- "$@"
else 
    test -n "$nnodes" || usage
    salloc -N$nnodes -p${partition} srun --propagate=CORE -N$nnodes ${PTY} $pepe -c $confpath -- "$@"
fi


# vi:tabstop=4 shiftwidth=4 expandtab
