#!/bin/bash

declare -r reqsock="ipc:///tmp/flux_request_uid$(id -u)"

while getopts "g" opt; do
    case ${opt} in
        \?) break;;
        g) CMDPREFIX="gdb -ex run --args";;
    esac
done


${CMDPREFIX} ./cmbd \
  --verbose \
  --child-uri=$reqsock \
  --rank=0 --size=1 \
  --hostlist=localhost \
  --plugins=modctl,api,barrier,kvs,log,hb,job,rexec,event,sched,rank \
  kvs:conf.hb.period-sec=1.5 \
  kvs:conf.log.reduction-timeout-msec=100 \
  kvs:conf.log.circular-buffer-entries=100000 \
  kvs:conf.log.persist-level=debug \
  rank:right-uri=$reqsock \
  sched:rdl-conf=conf/hype.lua
