#!/bin/bash -e

pids=""

flux module load -r all barrier
flux module load -r 0  content-sqlite
flux module load -r 0 kvs
flux module load -r all -x 0 kvs
flux module load -r all aggregator

#flux module load -r all live --barrier-count=$(flux getattr size)
flux module load -r all resource-hwloc & pids="$pids $!"
flux module load -r all job
flux module load -r 0 cron sync=hb

flux module load -r 0 userdb

wait $pids

core_dir=$(cd ${0%/*} && pwd -P)
all_dirs=$core_dir${FLUX_RC_EXTRA:+":$FLUX_RC_EXTRA"}
IFS=:
shopt -s nullglob
for rcdir in $all_dirs; do
    for rcfile in $rcdir/rc1.d/*; do
	echo running $rcfile
        $rcfile
    done
done
shopt -u nullglob
