#!/bin/sh

exit_rc=0

core_dir=$(cd ${0%/*} && pwd -P)
all_dirs=$core_dir${FLUX_RC_EXTRA:+":$FLUX_RC_EXTRA"}
IFS=:
for rcdir in $all_dirs; do
    for rcfile in $rcdir/rc3.d/*; do
	[ -e $rcfile ] || continue
        echo running $rcfile
        $rcfile || exit_rc=1
    done
done

flux modprobe rc3 || exit_rc=1

exit $exit_rc
