#!/usr/bin/env python3
##############################################################
# Copyright 2023 Lawrence Livermore National Security, LLC
# (c.f. AUTHORS, NOTICE.LLNS, COPYING)
#
# This file is part of the Flux resource manager framework.
# For details, see https://github.com/flux-framework.
#
# SPDX-License-Identifier: LGPL-3.0
##############################################################

"""
Print the strerror string for the given errno constant name.

For example:
  grep "flux_future_get: $(strerror_symbol ENOTSUP)" file
"""

import errno
import os
import sys

if len(sys.argv) != 2:
    print(
        "requires a single errno constant name or number and converts to strerror string"
    )

try:
    print(os.strerror(getattr(errno, sys.argv[1])))
    sys.exit(0)
except AttributeError:
    pass

val = int(sys.argv[1])
print(os.strerror(getattr(errno, errno.errorcode[val])))
