#!/bin/bash

# Simulated ssh command that ignores all options except the command
# and runs it locally

usage() {
    echo "Usage: tssh [-p port] [user@]hostname command..." >&2
    exit 1
}

while getopts "p:v" opt; do
    case ${opt} in
        p) port=${OPTARG} ;;
        *) usage ;;
    esac
done
userathost=$1
shift $((${OPTIND} - 1))
[ $# -gt 1 ] || usage
hostname=$1
shift

echo hostname=${hostname} >&2
[ -n "$port" ] && echo port=${port} >&2
echo cmd=\"$*\" >&2

unset FLUX_URI
exec $SHELL -c "$*"
