#!/bin/bash

# Simulated ssh command that ignores all options except the command
# and runs it locally

usage() {
    echo "Usage: tssh [-p port] [user@]hostname command..." >&2
    exit 1
}

#echo tssh: $* >&2

while getopts "p:v" opt; do
    case ${opt} in
        p) port=${OPTARG} ;;
        *) usage ;;
    esac
done
shift $((${OPTIND} - 1))
[ $# -gt 1 ] || usage
hostname=$1
shift

unset FLUX_URI
eval $*
