CMBD(1)
=======
:doctype: manpage


NAME
----
cmbd - Flux comms message broker daemon


SYNOPSIS
--------
*cmbd* ['OPTIONS']


DESCRIPTION
-----------
cmbd(1) is usually invoked indirectly, e.g. see flux-start(1).

cmbd(1) is a distributed message broker daemon that provides
communications services within a Flux comms session.  Flux jobs have
a dedicated comms session, while Flux light-weight jobs (LWJs) do not.

Resource manager services are implemented as dynamically loadable
plugins to cmbd(1), termed "comms modules".

cmbd(1) instances within a comms session are interconnected using
ZeroMQ sockets, and each is assigned a rank from 0 to size - 1.
The rank 0 node is the root of a tree-based overlay network.
In addition, there is a multicast pub/sub network for events, and
a ring network for debugging.  These networks may be accessed by
Flux commands and comms modules using Flux API services.

A periodic heartbeat event generated by rank 0 is used to synchronize
resource manager activities across the session.

A logging service aggregates Flux log messages across the session and
emits them to a configured destination on rank 0.

If cmbd(1) is executed with stdin attached to a tty, a shell is spawned.
*FLUX_TMPDIR* is set in the shell's environment so Flux commands run
by the shell can locate the Flux API socket belonging to rank 0.

OPTIONS
-------
*-h, --help*::
Summarize available options.

*-v, --verbose*::
Be annoyingly chatty.

*-q, --quiet*::
Suppress messages intended for interactive users.

*-t, --child-uri*='URI'::
Set the ZeroMQ endpoint to which this cmbd(1) instance will bind,
and tree based overlay network child cmbd(1) instances will connect.
In addition, the ring overlay network peers connect to this endpoint.

*-p, --parent-uri*='URI'::
Set the ZeroMQ endpoint to which this cmbd(1) will connect its
tree based overlay network.

*-r, --right-uri*='URI'::
Set the ZeroMQ endpoint to which this cmbd(1) will connect its
ring network.

*-e, --event-uri*='URI'::
On rank 0, set the ZeroMQ endpoint to which events will be published.
On other ranks, set the ZeroMQ endpoint from which events will be received.
Events are only published directly by rank 0; other ranks send a request
over the tree-based overlay network to rank 0 to publish by proxy.

*-S, --size*='N'::
Set the size of this comms session.

*-R, --rank*='N'::
Set the rank of this broker instance, 0 to size - 1.

*-k, --k-ary*='N'::
Set the branching factor of this comms session's tree based overlay
network (default 2).

*-H, --heartrate*='N.N'::
Set the session heartrate in seconds.  The valid range is 0.01 to 30.0
(default 2.0).

*-N, --sid*='NAME'::
Set the session id of this session (default "0").  The session id need
not be numerical.  The base name of *FLUX_TMPDIR* will be set to
"flux-'sid'-'rank'".

*-L, --logdest*='DEST'::
Set logging destination.  DEST may be 'syslog[:facility[:level]]',
'stderr', 'stdout', or a file name (default stderr).

*-M, --module*='NAME[nodeset]'::
Load the specified comms module.  '[nodeset]' optionally limits the
ranks on which the module should be loaded (default all ranks).
This option may be specified multiple times to load multiple modules.
The set of modules provided in the flux-core package are loaded by default.
Modules can also be loaded and unloaded on a live comms session with
flux-module(1).

*-O, --modopt*='NAME:key=val'::
Set an option for the comms module 'NAME'.  This option may be specified
multiple times to load multiple modules.

*-X, --module-path*='PATH'::
Override the compiled-in module search path (colon-separated).
The default is to search install paths.

*-s, --security*='MODE'::
Set the security mode.  The mode may be 'none', 'plain', or 'curve'
(default curve).  See flux-keygen(1) for more information.

*-p, --pmi-boot*::
Use PMI to obtain bootstrap configuration from a parent resource manager,
normally Flux or SLURM.

*-c, --command*='CMD'::
Execute "bash -c 'CMD'" on rank 0.

*-n, --noshell*::
Do not execute a shell on rank 0, even if stdin is a tty.

*-f, --force*::
If another cmbd is running in the same *FLUX_TMPDIR* space,
send it a SIGKILL and continue start-up.


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]
