FLUX(1)
=======
:doctype: manpage


NAME
----
flux - the Flux resource management framework


SYNOPSIS
--------
*flux* ['OPTIONS'] 'CMD' ['CMD-OPTIONS']


DESCRIPTION
-----------
Flux is a modular framework for resource management.
flux(1) is a front end for Flux sub-commands.
flux(1) itself has some general 'OPTIONS', described below.


OPTIONS
-------
*-h, --help*::
Display help on options, and a list of the core Flux sub-commands.

*-x, --exec-path*='PATH'::
Override the compiled-in search path for sub-commands.
Multiple directories are separated by colons.

*-M, --module-path*='PATH'::
Override the compiled-in search path for comms modules.
Multiple directories are separated by colons.

*-T, --tmpdir*='PATH'::
Run commands with 'FLUX_TMPDIR' set to 'PATH'.
When there are multiple message brokers on a node, this selects
which API socket to connect to.

*-t, --trace-apisock*::
Trace message sent back and forth to the message broker over the
API socket.  Trace output appears on stderr.

*-B, --cmbd-path*::
Override the compiled-in default path to the Flux message broker.

*-v, --verbose*::
Display Flux environment variable settings before 'CMD' is executed.


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]
