FLUX(1)
=======
:doctype: manpage


NAME
----
flux - the Flux resource management framework


SYNOPSIS
--------
*flux* ['OPTIONS'] 'CMD' ['CMD-OPTIONS']


DESCRIPTION
-----------
Flux is a modular framework for resource management.

flux(1) is a front end for Flux sub-commands.
"flux -h" summarizes the core Flux commands.
"flux help 'CMD'" displays the manual page for 'CMD'.

If 'CMD' contains a slash "/" character, it is executed directly,
bypassing the sub-command search path.


OPTIONS
-------
*-h, --help*::
Display help on options, and a list of the core Flux sub-commands.

*-v, --verbose*::
Display command environment, and the path search for 'CMD'.

*-c, --config*='DIR'::
Set the directory to be used for configuration.  The default is $HOME/.flux.

*-F, --file-config*::
Force configuration from file instead of KVS.

*-S, --secdir*='DIR'::
Set the directory to be used long-term keys.
The default is to use the config directory.

*-T, --tmpdir*='PATH'::
Run commands with 'FLUX_TMPDIR' set to 'PATH'.
When there are multiple message brokers on a node, this selects
which API socket to connect to.

*-t, --trace-apisock*::
Trace API socket traffic to 'stderr'.

*-x, --exec-path*='PATH'::
Prepend 'PATH' to sub-command executable search path.
Multiple directories may be specified, separated by colons.

*-M, --module-path*='PATH'::
Prepend 'PATH' to the comms module search path.
Multiple directories may be specified, separated by colons.

*-L, --lua-path*='PATH'::
Prepend 'PATH' to the Lua module search path (LUA_PATH).
Multiple paths may be specified, separated by semicolon.

*-C, --lua-cpath*='PATH'::
Prepend 'PATH' to the Lua binary module search path (LUA_CPATH).
Multiple paths may be specified, separated by semicolon.

*-B, --cmbd-path*='FILE'::
Override the path to the Flux communications broker daemon.


SUB-COMMAND ENVIRONMENT
-----------------------
flux(1) uses compiled-in install paths, configuration derived from a file
or the KVS, the environment, and its command line arguments to construct
the environment for sub-commands.

Sub-command search path::
Look for "flux-'CMD'" executable by searching a path constructed
with the following prototype:

  [--exec-path PATH]:[config.general.exec_path]:install-path

setenv FLUX_MODULE_PATH::
Set up broker comms module search path according to:

  [--module-path PATH]:[config.general.module_path]:install-path

setenv LUA_PATH::
Set Lua module search path:

  [--lua-path PATH];[config.general.lua_path]; \
    [getenv LUA_PATH];install-path;;;

setenv LUA_CPATH::
Set Lua binary module search path:

  [--lua-cpath PATH];[config.general.lua_cpath]; \
    [getenv LUA_CPATH];install-path;;;

setenv FLUX_CMBD_PATH::
Set the path to the broker executable.  This environment variable is
used by flux-start(1) and related sub-commands to launch the broker.
The path may be set by any of the following methods, in decreasing precedence:
- [--cmbd-path FILE]
- [config.general.cmbd_path]
- install-path

setenv FLUX_CONF_DIRECTORY::
Set the path to the Flux config directory, which contains a config
file and long term keys.  The path may be set by any of the following
methods, in descending precedence:
- [--config DIR]
- [$(top_builddir)/etc/flux, if being run from flux-core repo]
- [$HOME/.flux/config]

setenv FLUX_CONF_USEFILE::
Set to 1 if configuration was obtained from a file.

setenv FLUX_TRACE_APISOCK::
Set to "1" if --trace-apisock was specified.  This causes the FLUX_FLAGS_TRACE
flag to be set when an API socket is established by a sub-command.

setenv FLUX_TMPDIR::
Set if "--tmpdir" was specified.  The broker sets FLUX_TMPDIR when it
spawns child processes.  It specifies the directory where the API
socket for that broker can be found, among other things.  If running a
Flux sub-command from "outside" of a comms session, e.g. not as a process
descendant of the broker, you may need to set this to find the correct
API socket.


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]
