#!/bin/bash

if test $man_dir; then
    set ${man_dir}/*.[1-9]
fi

if test $# == 0; then
    echo "Usage: spellcheck file [file...]" >&2
    exit 1
fi

dict=${pws_dict:-./spell.en.pws}
if ! test -r $dict; then
   echo Dictionary $dict not found >&2
   exit 1
fi

if test  -z "$ASPELL"; then
   echo "1..$# # skip because aspell is not installed"
   exit 0
fi

exit_val=0
echo "1..$#"
count=1
for f in $*; do
    filename=$(basename $f)
    tmpfile=$(mktemp)
    rc=$(cat $f | aspell -p $dict -n list | sort | uniq | tee $tmpfile | wc -l)
    if test $rc == 0; then
        echo "ok $count - spell check $filename"
    else
	echo "not ok $count - spell check $filename failed"
        echo "---"
	exit_val=1
    fi
    cat $tmpfile | sed -e "s!^!$(basename $f): !"
    rm -f $tmpfile
    ((count++))
done

exit $exit_val
