// flux-help-description: Flux wreck convenience utilities
FLUX-WRECK(1)
=============
:doctype: manpage


NAME
----
flux-wreck - Flux wreck facility convenience utility


SYNOPSIS
--------
*flux* *wreck* 'COMMAND' ['OPTIONS']


DESCRIPTION
-----------
'flux wreck' is a convenience utility that operates on jobs in the
WRECK remote execution prototype. It can be used to gather information
about running and completed jobs directly from the Flux kvs.

flux-wreck(1) operates via a series of 'COMMANDS', described below:

COMMANDS
--------
*help* 'cmd'
Print help. If 'cmd' is provided, print help for that sub-command.

*ls* [-n, --max=COUNT] [JOBIDS...]::
Display a list of wreck jobs currently in kvs, along with their current
states. If '-n, --max' option is provided, then display at most 'COUNT'
jobs (default: 25). If an optional list of 'JOBIDS' is provided on the
command line, then display only those jobs.

*uri* [-n, --max=COUNT] [-b, --bare] [JOBIDS...]::
Display a list of wreck jobs currently in kvs, with abbreviated job info,
and a URI that can be used to contact the rank 0 broker if the job is a
Flux instance.  The field is blank for other types of jobs.
If '-n, --max' option is provided, then display at most 'COUNT'
jobs (default: 25). If '-b, --bare' option is provided, display only the
URI for a single job so that it can be parsed by scripts.  If an optional
list of 'JOBIDS' is provided on the command line, then display only those jobs.

*attach* [--status] [--label-io] 'jobid'::
Attach to output of a running or completed job. If input was not previously
connected, also attach to stdin. With '--status', also report job status
after dumping output. With '--label-io' label lines of output with taskid.

*status* 'jobid'::
Return the status of running or completed job 'jobid'. Prints the current
job status, and if exited, the exit codes of all tasks. This command will
exit with the highest exit code of all tasks.

*cancel* 'jobid'::
Make a request to the scheduler to cancel a pending job 'jobid'. Only supported
if a job scheduler module is loaded.

*kill* [--signal=N] 'jobid'::
Send SIGTERM to running job 'jobid'. If '--signal' is used, send signal 'N'
where 'N' may  be a signal number or name such as 'SIGKILL'.

*timing* [-n, --max=COUNT] [JOBIDS...]::
List timing information for lwj entries in Flux KVS. if '-n, --max' option is
provided, then display at most 'COUNT' jobs (default: 25). If an optional list
of 'JOBIDS' is provided on the command line, then display timing information
for only those jobs. This command lists four specific intervals in the wreck
job lifecycle:
 'STARTING'::: Time from LWJ entry creation until the job reaches the
              "starting" state. The "starting" state is when the first
              rexec daemon receives the request to launch tasks.
 'RUNNING'::: Time from "starting" to "running". The running state is
             reached when all rexec daemons have forked and executed
             all tasks.
 'COMPLETE'::: Time from "running" to "complete". This is the nominal time
              that tasks of the job actually ran.
 'TOTAL'::: This is the total time from job creation to the "completed" state.


*kvs-path* 'jobid'::
Display the path in the Flux KVS to the specified 'jobid'.

*last-jobid* [--kvs-path]::
Return the current value of the 'lwj' sequence number, that is the
last jobid allocated to a submitted wreck job.  With '--kvs-path',
report the path to job in kvs instead of jobid.  Other jobs may be
started between the time the id is obtained and when it is displayed
in this command, so 'last-jobid' should not be relied upon during real
workloads.

*purge* [OPTIONS...]::
Purge old job entries from Flux KVS. Without any options, the 'purge'
subcommand will print the current number of entries in the 'lwj.'
kvs directory. Otherwise, 'flux wreck purge' walks the list of all
completed jobs in the Flux KVS and selects the oldest (in terms of
completion time) as candidates for removal. The number of jobs selected
is dependent on the options below:

--verbose:::
-v:::
	Increase verbosity.

--target-size='COUNT':::
-t 'COUNT':::
	Set the target number of job entries to keep to 'COUNT'. The number
	of IDs to remove will be calculated based on target size, number of
	current job entries, and any maximum set on command line.

--remove:::
-R:::
	Perform an unlink of all selected job entries in KVS. This option is
	only valid if supplied with '--target-size'.

--max=N:::
-m N:::
	Set the maximum number of entries to remove on any one run.


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
--------
flux-wreckrun(1)
