FLUX-WRECK(1)
===========
:doctype: manpage


NAME
----
flux-wreck - Flux wreck facility convenience utility


SYNOPSIS
--------
*flux* *wreck* 'COMMAND' ['OPTIONS']


DESCRIPTION
-----------
'flux wreck' is a convenience utility that operates on jobs in the
WRECK remote execution prototype. It can be used to gather information
about running and completed jobs directly from the Flux kvs.

flux-wreck(1) operates via a series of 'COMMANDS', described below:

COMMANDS
--------
*help* 'cmd'
Print help. If 'cmd' is provided, print help for that sub-command.

*ls*
Display a list of wreck jobs currently in kvs, along with their current
states.

*attach* [--status] [--label-io] 'jobid'::
Attach to output of a running or completed job. If input was not previously
connected, also attach to stdin. With '--status', also report job status
after dumping output. With '--label-io' label lines of output with taskid.

*status* 'jobid'::
Return the status of running or completed job 'jobid'. Prints the current
job status, and if exited, the exit codes of all tasks. This command will
exit with the highest exit code of all tasks.

*kill* [--signal=N] 'jobid'::
Send SIGTERM to running job 'jobid'. If '--signal' is used, send signal 'N'
where 'N' may  be a signal number or name such as 'SIGKILL'.

*last-jobid*::
Return the current value of the 'lwj' sequence number, that is the last
jobid allocated to a submitted wreck job. Other jobs may be started
between the time the id is obtained and when it is displayed in this
command, so 'last-jobid' should not be relied upon during real workloads.

AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]
