FLUX-CONFIG(1)
==============
:doctype: manpage


NAME
----
flux-config - manipulate the Flux configuration


SYNOPSIS
--------
*flux* *config* COMMAND ['OPTIONS']


DESCRIPTION
-----------
Flux configuration is stored in the KVS under the 'config.*' name space.

A comms session initializes its KVS config space either by cloning that
of its parent, or from a static config file.  flux-config(1) can operate
directly on either; use flux(1) options to select which.

Keys are hierarchical, and use a period "." as path separator.
Values are always strings.

OPTIONS
-------
*-v, --verbose*::
Note where the config source or destination as it is read or written.

COMMANDS
--------
*dump*::
Parse the config file and dump its contents, either the entire file,
or from 'path' on down.

*get* 'key'::
Print the value for 'key'.  Return an error if 'key' does not exist
in the configuration.

*put* 'key=val'::
Assign the value 'val' to 'path'.  Any existing value is overwritten.
The config file is created if it does not exist.

*save* ['directory']::
Save the configuration to a new place.  If a directory is not specified,
the directory configured by flux(1) is be used.


CONFIG FILE
-----------
The config file uses the hierarchical ZPL format (see below).
All keys and values are strings.  Hierarchy is expressed in the file
with 4-character indentation.  Comments are lines that begin with a "#".
For example:

  general
      exec_path = "/tmp/flux/src/cmd:/tmp/flux-core/src/cmd"
      cmbd_path = "/tmp/flux/src/broker/cmbd"
      lua_cpath = "/tmp/flux/src/bindings/lua/.libs/?.so"
      lua_path = "/tmp/flux/src/bindings/lua/?.lua"
      module_path = "/tmp/flux/src/modules/api/.libs:/t..."
      man_path = "/tmp/flux/doc"

Translated to the KVS 'config.*' space:

  config.general.exec_path = "/tmp/flux/src/cmd:/tmp/flux-core/src/cmd"
  config.general.cmbd_path = "/tmp/flux/src/broker/cmbd"
  config.general.lua_cpath = "/tmp/flux/src/bindings/lua/.libs/?.so"
  config.general.lua_path = "/tmp/flux/src/bindings/lua/?.lua"
  config.general.module_path = "/tmp/flux/src/modules/api/.libs:/t..."
  config.general.man_path =  "/tmp/flux/doc"
  

AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
--------
flux(1)

http://rfc.zeromq.org/spec:4/ZPL
