// flux-help-include: true
FLUX-KVS(1)
===========
:doctype: manpage


NAME
----
flux-kvs - Flux key-value store utility


SYNOPSIS
--------
*flux* *kvs* 'COMMAND' ['OPTIONS']


DESCRIPTION
-----------
The Flux key-value store (KVS) is a simple, distributed data storage
service used a building block by other Flux components.
flux-kvs(1) is a command line utility that operates on the KVS.
It is a very thin layer on top of a C API.

The Flux KVS stores JSON values under string keys.  The keys are
hierarchical, using "." as a path separator, analogous to "/" separated
UNIX file paths.  A single "." represents the root directory of
the KVS.

The KVS is distributed among the ranks of a comms session.  Rank 0
is the master, and other ranks are caching slaves.  All writes are flushed
to the master during a commit operation.  Data is stored in a hash tree
such that every commit results in a new root hash.  Each new root hash
is multicast across the session.  When slaves update their root hash,
they atomically update their view to match the master.  There may be a
delay after a commit while old data is served on a slave that has not yet
updated its root hash, thus the Flux KVS consistency model is "eventually
consistent".  Slaves cache data temporally and fault in new data through
their parent in the overlay network.

flux-kvs(1) runs a KVS 'COMMAND'.  The possible commands and their
arguments are described below.

COMMANDS
--------
*get* 'key' ['key...']::
Retrieve the value stored under 'key'.  If nothing has been stored under
'key', display an error message.

*type* 'key' ['key...']::
Display the JSON type of the value under key: 'null', 'boolean', 'double',
'int', 'object', 'array', or 'string'.  If nothing has been stored under
'key', display an error message.

*put* 'key=value' ['key=value...']::
Store 'value' under 'key' and commit it.  If it already has a value,
overwrite it.

*dir* [-r] ['key']::
Display all keys and their values under the directory 'key'.
If 'key' does not exist or is not a directory, display an error message.
If 'key' is not provided, "." (root of the namespace) is assumed.  If '-r'
is specified, recursively display keys under subdirectories.

*dirsize* 'key'::
Get the number of keys in a directory.

*unlink* 'key' ['key...']::
Remove 'key' from the KVS and commit the change.  If 'key' represents
a directory, remove all keys underneath it.  If nothing has been stored
under 'key', do nothing (it is not an error).

*link* 'target' 'linkname'::
Create a new name for 'target', similar to a symbolic link, and commit
the change.  'target' does not have to exist.  If 'linkname' exists,
it is overwritten.

*readlink* 'key'::
Retrieve the key a link refers to rather than its value, as would be
returned by *get*.

*mkdir* 'key'::
Create an empty directory and commit the change.  If 'key' exists,
it is overwritten.

*watch* 'key'::
Watch 'key', displaying each change on a line of output.
If the key is not set, display "NULL".  This command runs forever.

*copy-tokvs* 'key' 'file'::
Copy data from 'file' to 'key', encoding to Z85 format and committing
the change.  'file' may be a UNIX file name or "-" indicating standard
input.

*copy-fromkvs* 'key' 'file'::
Copy data from 'key' to 'file', decoding from Z85 format.
'file' may be a UNIX file name or "-" indicating standard output.

*version*::
Display the current KVS version, an integer value.  The version starts
at zero and is incremented on each KVS commit.  Note that some commits
may be aggregated for performance and the version will be incremented
once for the aggregation, so it cannot be used as a direct count of
commit requests.

*wait* 'version'::
Block until the KVS version reaches 'version' or greater.  A simple form
of synchronization between peers is:  node A puts a value, commits it,
reads version, sends version to node B.  Node B waits for version, gets
value.

*dropcache*::
Tell the local KVS to drop any cache it is holding.

*dropcache-all*::
Send an event across the comms session instructing all KVS instances
to drop their caches.

*copy* 'source' 'destination':: 
Copy 'source' key to 'destination' key.  If a directory is copied, a new
reference is created; it is unnecessary for *copy* to recurse into 'source'.

*move* 'source' 'destination':: 
Like *copy*, but 'source' is unlinked after the copy.

*get-treeobj* 'key'::
Retrieve the directory entry associated with 'key'.
A treeobj should be treated as an opaque string value, which
may contain spaces.

*put-treeobj* 'key="treeobj"'::
Associate a new treeobj with 'key', overwriting the previous treeobj,
if any.  A treeobj should be treated as an opaque string value, which
may contain spaces.

*getat* 'treeobj' 'key'::
Retrieve the value stored under 'key', starting the lookup at 'treeobj'.
If nothing has been stored under 'key', display an error message.

*dirat* [-r] 'treeobj' ['key']::
Display all keys and their values under the directory 'key', starting
lookup at 'treeobj'.  If 'key' does not exist or is not a directory,
display an error message.  If 'key' is not provided, "." (root of
the namespace) is assumed.  If '-r' is specified, recursively display
keys under subdirectories.

*readlinkat* 'treeobj' 'key'::
Retrieve the key a link refers to rather than its value, as would be
returned by *get*, starting lookup at 'treeobj'.


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]
