// flux-help-include: true
FLUX-PING(1)
============
:doctype: manpage


NAME
----
flux-ping - measure round-trip latency to Flux services


SYNOPSIS
--------
*flux* *ping* ['OPTIONS'] target


DESCRIPTION
-----------
flux-ping(1) measures round-trip latency to a Flux service implementing
the "ping" method in a manner analogous to ping(8).  The ping response is
essentially an echo of the request, with the route taken to the service
added by the service.  This route is displayed in the output and can
give insight into how various addresses are routed.

'target' may be the name of a comms module service, e.g. "kvs" or "live".
flux-ping(1) will send a request to "kvs.ping" or "live.ping".
As a shorthand, 'target' can include a rank or nodeset prefix delimited by an
exclamation point.  "flux ping 4!kvs" is equivalent to
"flux ping --rank 4 kvs" (see --rank option below).
Don't forget to quote the exclamation point if it is interpreted by your shell.

As a shorthand, 'target' may also simply be a rank or nodeset by itself
indicating that the broker on that rank or ranks, rather than a comms
module, is to be pinged.  "flux ping 0-15" is equivalent to
"flux ping --rank 0-15 cmb".

OPTIONS
-------
*-r, --rank*'=NODESET'::
Find target on a specific broker rank(s).  See NODESET FORMAT below
for more information.  Special case strings ``_any_'' and
``_upstream_'' available to ping FLUX_NODEID_ANY and
FLUX_NODEID_UPSTREAM respectively.  Default: send to ``_any_''.

*-p, --pad*'=N'::
Include in the payload a string of length 'N' bytes.  The payload will be
echoed back in the response.  This option can be used to explore the
effect of message size on latency.  Default: no padding.

*-i, --interval*'=N'::
Specify the delay, in seconds, between successive requests.
A value of zero is valid and indicates that there should be no delay.
Requests are sent without waiting for responses.  Default: 1.0 seconds.

*-c, --count*'=N'::
Specify the number of requests to send, and terminate the command once
responses have been received for all the requests.  Default: unlimited.

*-b, --batch*::
Begin processing responses after all requests are sent.  Requires --count.

EXAMPLES
--------

One can ping a service by name, e.g.

  $ flux ping kvs
  kvs.ping pad=0 seq=0 time=0.774 ms (0EB02!A3368!0!382A6)
  kvs.ping pad=0 seq=1 time=0.686 ms (0EB02!A3368!0!382A6)
  ...

This tells you that the local "kvs" comms module is alive and the
round-trip latency is a bit over half a millisecond.  The route hops are:

  0EB02: UUID of the ping command
  A3368: UUID of the API module
  0:     rank of the local broker
  382A6: UUID of the KVS module.

One can direct a ping request to a nodeset, e.g.

  $ flux ping 0-7
  0-7!cmb.ping pad=0 seq=0 time=(0.413:1.180:2.097) ms stddev 0.503
  0-7!cmb.ping pad=0 seq=1 time=(0.397:1.334:2.150) ms stddev 0.499
  ...

This tells you that the message brokers on ranks 0-7 are responsive.
The time shows the statistical breakdown of RTT values for the set of
responses in (min:mean:max) format.


NODESET FORMAT
--------------
include::NODESET.adoc[]


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]
