// flux-help-command: proxy
// flux-help-description: Create proxy environment for Flux instance
FLUX-PROXY(1)
=============
:doctype: manpage


NAME
----
flux-proxy - create proxy environment for Flux instance


SYNOPSIS
--------
*flux* *proxy* [OPTIONS] URI [command [args...]]


DESCRIPTION
-----------
*flux proxy* connects to the Flux instance identified by _URI_,
then spawns a shell with FLUX_URI pointing to a local:// socket
managed by the proxy program.  As long as the shell is running,
the proxy program routes messages between the instance and the
local:// socket.  Once the shell terminates, the proxy program
terminates and removes the socket.

The purpose of *flux proxy* is to allow a connection to be reused,
for example where connection establishment has high latency or
requires authentication.


OPTIONS
-------
*-s, --stdio*::
Instead of creating a local:// proxy socket, assume
that a single client is already connected to stdin and
stdout.  This mode is used by the ssh:// connector.

*-e, --setenv*='NAME=VALUE'::
Set NAME to VALUE in the environment before interpreting the
_job_ argument or connecting to the Flux instance.  This
is mainly useful when connecting into a remote environment
with the ssh:// connector.


EXAMPLES
--------

Connect to a job running on the localhost which has a FLUX_URI
of local:///tmp/flux-123456-abcdef/0 and spawn an interactive
shell:

  $ flux proxy local:///tmp/flux-123456-abcdef/0

Connect to the same job remotely on host foo.com:

  $ flux proxy ssh://foo.com/tmp/flux-123456-abcdef/0


USE BY SSH CONNECTOR
--------------------

The ssh:// connector spawns *flux proxy --stdio* as the remote
command.  The ssh URI may contain the following components:

  ssh://[user@]hostname[:port][/path][?setenv=NAME=VALUE]

These components translate to *ssh* and *flux proxy*
arguments as follows:

  ssh [-p port] [user@]hostname flux proxy --stdio \
         [--setenv=NAME=VAL] [/path]

The ssh connector understand the following environment variables:

*FLUX_SSH*::
Override the default ssh program.  The ssh program is
executed with only the following arguments:

  ssh [-p port] [user@]hostname COMMAND ...

The default ssh program is "/usr/bin/rsh".

*FLUX_SSH_RCMD*::
Set the name of the remote *flux* program.  If this is not set,
the same path that *flux* is found locally will be used remotely.


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]

