// flux-help-description: submit job requests to a scheduler
FLUX-SUBMIT(1)
==============
:doctype: manpage


NAME
----
flux-submit - Flux utility for submitting job requests to a scheduler


SYNOPSIS
--------
[verse]
'flux submit' [-n <ntasks>] [-N <nnodes>] [-t <tasks-per-node>]
                [-o|--options='OPTIONS']
                [-O|--output='FILENAME'] [-E|--error='FILENAME']
                [-i|--input='HOW'] ['COMMANDS'...]


DESCRIPTION
-----------

'flux submit' is the front-end command for submitting jobs to
a Flux comms session for eventual execution by a Flux scheduler.
Once a job has been scheduled for execution, it will be executed
using the WRECK remote execution prototype. 

See flux-wreckrun(1) for more information about execution
method.

OPTIONS
-------

--ntasks='ntasks'::
-n 'ntasks'::
	Request to run a total of 'ntasks' tasks. If '--ntasks' is used alone,
	i.e. without '--nnodes', then 'flux submit' will attempt to
	distribute the 'ntasks' tasks across all nodes of the Flux comms
	session.

--nnodes='nnodes'::
-N 'nnodes'::
	Request to run across 'nnodes' nodes in the current comms session.
	
--tasks-per-node='tpn'::
-t 'tpn'::
	Set the number of tasks to run per node to 'tpn'. The default is
	--tasks-per-node=1. This value is overridden by '--ntasks' if used.

--labelio::
-l::
	Prepend stdout and stderr output lines with the task id to which
	the output belongs.

--output='FILENAME'::
-O 'FILENAME'::
	Duplicate stdout and stderr from tasks to a file or files. 'FILENAME'
	is optionally a mustache template which expands the keys 'id', 'cmd'
	and 'taskid'. (e.g. '--output=flux-{{id}}.out')

--error='FILENAME'::
-E 'FILENAME'::
	Send stderr to a different location than stdout.

--input='HOW'::
-i 'HOW'::
	Indicate how to deal with stdin for tasks. 'HOW' is a list of 'src:dst'
	pairs where 'src' is a source 'FILENAME' which may optionally be a
	mustache template as in `--output`, or the special term `stdin` to
	indicate the stdin from a front end program, and 'dst' is a list of
	taskids or `*` or `all` to indicate all tasks. The default is `stdin:*`.
	If only one of 'src' or 'dst' is specified, a heuristic is used to
	determine whether a list of tasks or an input file was meant. (e.g
	`--input=file.in` will use `file.in` as input for all tasks, and
	`--input=0` will send stdin to task 0 only.

--walltime='N[SUFFIX]'::
-T 'N[SUFFIX]'::
        Set max job walltime to N seconds. Optional suffix may be 's'
        for seconds (default), 'm' for minutes, 'h' for hours or 'd'
        for days.  N may be an arbitrary floating point number, but
        will be rounded up to nearest second.

--options='options,...'::
-o 'options,...'::
	Apply extended job options to the current execution. Examples of
	these options are described in the xref:extra-options[].

EXTRA OPTIONS
-------------
[[extra-options]]

Extra options can be supplied on the `flux submit` command via the
'--options' command line option. Multiple options should be separated
via commas. Currently available options include:

'stdio-commit-on-open'::
	Commit to kvs on stdio open in each task. The default is to
	delay commit. Without this option, stdio files for jobs will
	not appear in KVS on all nodes until the next KVS commit.
	The default behavior avoids a kvs commit storm as stdout and
	stderr files are opened for every task.

'stdio-commit-on-close'::
	Commit to kvs for each stdio stream as it gets EOF. The default
	is to delay the commit. Without this option, stdio files for
	jobs will not appear to close until after the next natural
	KVS commit. The default behavior avoids a kvs commit storm
	as stdout and stderr files are closed from many tasks. This
	option may need to be enabled if you need to detect immediately
	when a stdout or stderr stream is closed from a task.

'stdio-delay-commit'::
	Disable commit to kvs for each line of output. The default
	behavior is to call kvs_commit() after each line of output
	from every task. If many tasks are writing multiple lines
	of output and it is not necessary to see lines of output
	as they are generated, it will speed up job execution to
	enable this option.

'commit-on-task-exit'::
	Commit to the kvs for each task exit event. The default behavior
	is to write the task exit status to the kvs as each task in
	a lightweight job exits, but delay kvs commit. This avoids
	a kvs commit storm when many tasks are exiting simultaneously.
	This option may need to be enabled if knowlege of exit status or
	fact that tasks have exited is required in real time.

'stop-children-in-exec'::
	Start tasks in a STOPPED state waiting for attach from a
	debugger. This option is provided for use with parallel
	debuggers such as TotalView.

'no-aggregate-task-exit'::
        Do not use aggregator for task exit messages.  This option
        will result in each task's exit status being commited
        separately into the kvs.

'no-pmi-server'::
        Do not start simple pmi server.  This option can be used to
        not launch the pmi server if a non-MPI job is being run.

'trace-pmi-server'::
        Log simple pmi server protocol exchange.  This option is used
        for debugging.

AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]

SEE ALSO
--------
flux-wreckrun(1), flux-wreck(1)
