// flux-help-command: hwloc
// flux-help-description: Control/query resource-hwloc service
FLUX-HWLOC(1)
=============
:doctype: manpage


NAME
----
flux-hwloc - Control/query resource-hwloc service


SYNOPSIS
--------
*flux* *hwloc* *lstopo* ['lstopo-OPTIONS']

*flux* *hwloc* *reload* ['OPTIONS'] ['DIR']

*flux* *hwloc* *topology* ['OPTIONS']


DESCRIPTION
-----------
The Flux `resource-hwloc` module collects system topology at
each flux-broker using the Portable Hardware Locality (hwloc)
library.

The *flux hwloc* command offers simple interfaces to query and
control this hwloc data.

COMMANDS
--------

*flux hwloc* requires a 'COMMAND' argument. The supported commands
are

*lstopo*::
Run `lstopo(1)` against the full hardware hierarchy configured in the
current Flux instance. Extra `OPTIONS` are passed along to the system
`lstopo(1)`. + 
By default, *flux hwloc lstopo* generates console output.
For graphical output, try:  *flux hwloc lstopo --of graphical*.

*reload* ['OPTIONS'] ['DIR']::
Reload hwloc topology information, optionally loading hwloc XML files
from `DIR/<rank>.xml` files.
Options:

 --rank='NODESET':::
 -r 'NODESET':::
 Only reload XML on provided 'NODESET'.

 --walk-topology=['yes|no']:::
 -t ['yes|no']:::
 If 'yes', force resource-hwloc module to walk full topology on each reloaded
 rank and insert broken down topology into KVS under. If 'no', force disable
 the topology walk if enabled by default in module.

*topology*::
Dump current aggregate topology XML for the current session to stdout.


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]


SEE ALSO
--------
lstopo(1), hwloc: https://www.open-mpi.org/projects/hwloc/
