// flux-help-include: true
FLUX-KVS(1)
===========
:doctype: manpage


NAME
----
flux-kvs - Flux key-value store utility


SYNOPSIS
--------
*flux* *kvs* 'COMMAND' ['OPTIONS']


DESCRIPTION
-----------
The Flux key-value store (KVS) is a simple, distributed data storage
service used a building block by other Flux components.
flux-kvs(1) is a command line utility that operates on the KVS.
It is a very thin layer on top of a C API.

The Flux KVS stores JSON values under string keys.  The keys are
hierarchical, using "." as a path separator, analogous to "/" separated
UNIX file paths.  A single "." represents the root directory of
the KVS.

The KVS is distributed among the ranks of a comms session.  Rank 0
is the master, and other ranks are caching slaves.  All writes are flushed
to the master during a commit operation.  Data is stored in a hash tree
such that every commit results in a new root hash.  Each new root hash
is multicast across the session.  When slaves update their root hash,
they atomically update their view to match the master.  There may be a
delay after a commit while old data is served on a slave that has not yet
updated its root hash, thus the Flux KVS consistency model is "eventually
consistent".  Slaves cache data temporally and fault in new data through
their parent in the overlay network.

flux-kvs(1) runs a KVS 'COMMAND'.  The possible commands and their
arguments are described below.

COMMANDS
--------
*get* 'key' ['key...']::
Retrieve the value stored under 'key'.  If nothing has been stored under
'key', display an error message.

*put* 'key=value' ['key=value...']::
Store 'value' under 'key' and commit it.  If it already has a value,
overwrite it.

*dir* [-r] [-d] ['key']::
Display all keys and their values under the directory 'key'.
If 'key' does not exist or is not a directory, display an error message.
If 'key' is not provided, "." (root of the namespace) is assumed.  If '-r'
is specified, recursively display keys under subdirectories.  If '-d' is
specified, do not output key values.

*unlink* 'key' ['key...']::
Remove 'key' from the KVS and commit the change.  If 'key' represents
a directory, remove all keys underneath it.  If nothing has been stored
under 'key', do nothing (it is not an error).

*link* 'target' 'linkname'::
Create a new name for 'target', similar to a symbolic link, and commit
the change.  'target' does not have to exist.  If 'linkname' exists,
it is overwritten.

*readlink* 'key' ['key...']::
Retrieve the key a link refers to rather than its value, as would be
returned by *get*.

*mkdir* 'key' ['key...']::
Create an empty directory and commit the change.  If 'key' exists,
it is overwritten.

*watch* [-o] [count] 'key'::
Watch 'key', displaying each change on a line of output.  If the key
is not set, display "NULL".  If 'count' is specified, display at most
'count' changes.  Otherwise, command runs forever.  If '-o' is
specified, output the current value before outputting changes.

*watch-dir* [-r] [-d] [-o] [count] 'key'::
Watch directory specified at 'key', displaying changes within it and
in subdirectories.  If '-r' is specified, recursively display keys
under subdirectories.  If '-d' is specified, do not output key values.
If 'count' is specified, display at most 'count' changes.  Otherwise,
this command runs forever.  If '-o' is specified, output the current
value before outputting changes.

*version*::
Display the current KVS version, an integer value.  The version starts
at zero and is incremented on each KVS commit.  Note that some commits
may be aggregated for performance and the version will be incremented
once for the aggregation, so it cannot be used as a direct count of
commit requests.

*wait* 'version'::
Block until the KVS version reaches 'version' or greater.  A simple form
of synchronization between peers is:  node A puts a value, commits it,
reads version, sends version to node B.  Node B waits for version, gets
value.

*dropcache*::
Tell the local KVS to drop any cache it is holding.

*dropcache-all*::
Send an event across the comms session instructing all KVS instances
to drop their caches.

*copy* 'source' 'destination':: 
Copy 'source' key to 'destination' key.  If a directory is copied, a new
reference is created; it is unnecessary for *copy* to recurse into 'source'.

*move* 'source' 'destination':: 
Like *copy*, but 'source' is unlinked after the copy.


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]
