// flux-help-description: Invoke Flux comms message broker daemon
FLUX-BROKER(1)
==============
:doctype: manpage


NAME
----
flux-broker - Flux comms message broker daemon


SYNOPSIS
--------
*flux-broker* ['OPTIONS'] ['initial-program' ['args...']]


DESCRIPTION
-----------
flux-broker(1) is a distributed message broker daemon that provides
communications services within a Flux comms session.  It may be
launched as a parallel program under Flux or other resource managers
that support PMI.

Resource manager services are implemented as dynamically loadable
plugins to flux-broker(1), termed "comms modules".

flux-broker(1) instances within a comms session are interconnected using
ZeroMQ sockets, and each is assigned a rank from 0 to size - 1.
The rank 0 node is the root of a tree-based overlay network.
In addition, there is a multicast pub/sub network for events, and
a ring network for debugging.  These networks may be accessed by
Flux commands and comms modules using Flux API services.

A periodic heartbeat event generated by rank 0 is used to synchronize
resource manager activities across the session.

A logging service aggregates Flux log messages across the session and
emits them to a configured destination on rank 0.

After its overlay networks have completed wire-up, flux-broker(1)
starts the initial program on rank 0.  If none is specified on
the broker command line, an interactive shell is launched.


OPTIONS
-------
*-h, --help*::
Summarize available options.

*-v, --verbose*::
Be annoyingly chatty.

*-q, --quiet*::
Suppress messages intended for interactive users.

*-N, --sid*='NAME'::
Set the session id of this session.

*-k, --k-ary*='N'::
Set the branching factor of this comms session's tree based overlay
network (default: 2).

*-H, --heartrate*='N.N'::
Set the session heartrate in seconds.  The valid range is 0.01 to 30.0
(default: 2.0).

*-L, --logdest*='DEST'::
Set log destination.  DEST may be 'stderr' or a file name (default: stderr).

*-l, --log-level*='LEVEL'::
Log messages of LEVEL or below are forwarded to rank 0 and sent to the
configured log destination.  LEVEL may be an integer (0-7) or the name
of a syslog(3) level, e.g.  0=emerg, 1=alert, 2=crit, 3=err, 4=warning,
5=notice, 6=info, 7=debug (default: 6).

*-M, --module*='NAME[nodeset]'::
Load the specified comms module.  '[nodeset]' optionally limits the
ranks on which the module should be loaded (default all ranks).
This option may be specified multiple times to load multiple modules.
The set of modules provided in the flux-core package are loaded by default.
Modules can also be loaded and unloaded on a live comms session with
flux-module(1).

*-O, --modopt*='NAME:key=val'::
Set an option for the comms module 'NAME'.  This option may be specified
multiple times to load multiple modules.

*-X, --module-path*='PATH'::
Override the compiled-in module search path (colon-separated).
The default is to search install paths.

*-x,--exclude*='NAME'::
Do not load the specified comms module.

*-s, --security*='MODE'::
Set the security mode.  The mode may be 'none', 'plain', or 'curve'
(default: curve).  See flux-keygen(1) for more information.

*-m, --boot-method*='METHOD'::
Select the method used to determine rank, size, session id, and
overlay wire-up information.  Valid methods are SINGLE and PMI.
(default: PMI).

*-E, --enable-epgm*::
Enable EPGM, a reliable multicast protocol, for event distribution.
Without this option, the tree-based overlay network distributes events.
On large sessions, EPGM should improve scalability and reduce system jitter,
however it requires that network switches support multicast and currently
uses a naive algorithm to select a unique multicast port for the session.
This algorithm should be safe for instances launched directly by the
"native" resource manager using the PMI boot method, but not yet for
instances launched by those instances.   The first network interface
associated with the hostname is used, and the multicast address is
hardwired to 239.192.1.1.

*-I, --shared-ipc-namespace*::
Enable the use of ipc:// sockets for the tree-based overlay network
and event distribution.  This may be set if all ranks of a comms
session share a common $TMPDIR namespace.

*-D, --socket-directory*='DIR'::
Create ipc:// sockets in this directory.  If unspecified, ranks co-located
in the same $TMPDIR namespace will use unique socket directories.

*-g, --shutdown-grace*='SECS'::
Specify the shutdown grace period, in seconds (default: guess based
on session size).


AUTHOR
------
This page is maintained by the Flux community.


RESOURCES
---------
Github: <http://github.com/flux-framework>


COPYRIGHT
---------
include::COPYRIGHT.adoc[]
