EXTRA OPTIONS
-------------
[[extra-options]]

Extra options can be supplied on the `flux wreckrun` command via the
'--options' command line option. Multiple options should be separated
via commas. Currently available options include:

'cpu-affinity[=per-task]'::
	Set default CPU affinity of all tasks to the cores allocated
        to the job. With 'cpu-affinity=per-task' distribute tasks
        across allocated cores using 'hwloc_distrib(3)'.

'gpubind=[per-task,off]'::
	By default, if GPU devices are allocated to a job, the environment
	variable CUDA_VISIBLE_DEVICES is set to the list of allocated
	GPUs. The 'gpubind' option may be used to disable this behavior
	'-o gpubind=off', or can request that the GPUs be distributed
	among the local tasks with '-o gpubind=per-task'.

'mpi'::
	Select an MPI type being run if necessary. Some MPI "plugins"
	are not enabled by default, and this option may be used to
	enable them, e.g. '-o mpi=spectrum'.

'stdio-commit-on-open'::
	Commit to kvs on stdio open in each task. The default is to
	delay commit. Without this option, stdio files for jobs will
	not appear in KVS on all nodes until the next KVS commit.
	The default behavior avoids a kvs commit storm as stdout and
	stderr files are opened for every task.

'stdio-commit-on-close'::
	Commit to kvs for each stdio stream as it gets EOF. The default
	is to delay the commit. Without this option, stdio files for
	jobs will not appear to close until after the next natural
	KVS commit. The default behavior avoids a kvs commit storm
	as stdout and stderr files are closed from many tasks. This
	option may need to be enabled if you need to detect immediately
	when a stdout or stderr stream is closed from a task.

'stdio-delay-commit'::
	Disable commit to kvs for each line of output. The default
	behavior is to call kvs_commit() after each line of output
	from every task. If many tasks are writing multiple lines
	of output and it is not necessary to see lines of output
	as they are generated, it will speed up job execution to
	enable this option.

'commit-on-task-exit'::
	Commit to the kvs for each task exit event. The default behavior
	is to write the task exit status to the kvs as each task in
	a lightweight job exits, but delay kvs commit. This avoids
	a kvs commit storm when many tasks are exiting simultaneously.
	This option may need to be enabled if knowlege of exit status or
	fact that tasks have exited is required in real time.

'stop-children-in-exec'::
	Start tasks in a STOPPED state waiting for attach from a
	debugger. This option is provided for use with parallel
	debuggers such as TotalView.

'no-pmi-server'::
        Do not start simple pmi server.  This option can be used to
        not launch the pmi server if a non-MPI job is being run.

'trace-pmi-server'::
        Log simple pmi server protocol exchange.  This option is used
        for debugging.
