#!/bin/bash
set -e # Exit immediately if a command exits with a non-zero status.

GITROOT=$(git rev-parse --show-toplevel)
cd $GITROOT

if command -v clang-format 2>&1 > /dev/null ; then
    find src t -name "*.c" -o -name "*.h" | grep -v -Ef .vendored-files \
        | xargs clang-format -style=file -output-replacements-xml \
        | ( ! grep -c "<replacement " >/dev/null )
else
    echo "clang-format not found, failing"
    exit 1
fi

if command -v black 2>&1 > /dev/null ; then
    # awk cmd copied from:
    # https://unix.stackexchange.com/questions/66097/find-all-files-with-a-python-shebang
    find src t -type f \
         \( -name "*.py" -print -o \
         -exec awk ' /^#!.*python/{print FILENAME} {nextfile}' {} + \) \
        | xargs black --check
else
  echo "black not found, failing"
  exit 1
fi
