#!/bin/bash
set -e

if command -v black 2>&1 > /dev/null ; then
    # awk cmd copied from:
    # https://unix.stackexchange.com/questions/66097/find-all-files-with-a-python-shebang
    find src t -type f \
         \( -name "*.py" -print -o \
         -exec awk ' /^#!.*python/{print FILENAME} {nextfile}' {} + \) \
        | xargs black --check
else
  echo "black not found, failing"
  exit 1
fi
