#!/bin/bash -e

pylint=$(command -v pylint3 pylint | head -1)
if test -n "$pylint"; then
    $pylint --rcfile=scripts/.pylintrc src/bindings/python/flux

    # awk cmd copied from:
    # https://unix.stackexchange.com/questions/66097/find-all-files-with-a-python-shebang
    find src/cmd -type f \( -name "*.py" -print -o \
         -exec awk ' /^#!.*python/{print FILENAME} {nextfile}' {} + \) \
        | xargs $pylint --rcfile=scripts/.pylintrc --disable=missing-docstring,no-member --module-rgx='[a-z-]+'
else
  echo "pylint not found, python left unlinted"
fi
