on:
  pull_request:
  push:
    branches:
      - master
name: asan
jobs:
  check-asan:
    name: address-sanitizer check
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - run: git fetch --tags || true
    - name: disable ASLR
      run: |
        sudo sysctl -w kernel.randomize_va_space=0
    - name: docker-run-checks with ASan
      timeout-minutes: 40
      env:
        PRELOAD: /usr/lib64/libasan.so.8
        ASAN_OPTIONS: detect_leaks=0,start_deactivated=true,replace_str=true,verify_asan_link_order=false
        FLUX_TEST_TIMEOUT: 300
        TAP_DRIVER_QUIET: t
      run: >
        src/test/docker/docker-run-checks.sh \
          --image=fedora36 --unit-test-only -j4 \
          -- --with-flux-security --enable-sanitizer=address

    - name: after failure
      if: failure() || cancelled()
      run: src/test/checks-annotate.sh

